### ISSUE TITLE
Taxonomy admin view does not allow to change order + shift parent terms anymore

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#101]
I tried to add some legislation categories to the LL resource type taxonomy. But since the admin view shows the amount of resources (which is great), it doesn't show the sublevels anymore: https://landportal.info/taxonomy/term/7890/edit

 I can add a parent term to a new term, but I can't influence the order in which it shows. Now "other" is in the middle, while I had it nicely arranged to it was in order of weight of the laws.

Any ideas how I can change this back?

**Comment by lisettemeij** [comment]
Just to reiterate this: it looks horrible at the moment, everything is completely out of order and I can't change it. Anyone available to fix this?

**Comment by jcr** [comment]
it's back to the more Drupal "default" view
