### ISSUE TITLE
Curation of License and Copyright field of Land Library resource

### ISSUE THREAD

**Issue by dayures** [landportal/drupal#102]
The values and intention of the License and Copyright fields should be curated. @lisettemeij maybe we can go ahead in the next clean day with the support of @jcr for the Drupal Admin views

**Comment by lisettemeij** [comment]
I would suggest to include Nicholas in this discussion when he comes on board in September. Personally I am really not an expert in copyright law (other than the basics in Dutch law) - so I think it would be good to include another lawyer and do this right :)

**Comment by dayures** [comment]
@lisettemeij should we just "rename" the field from "Copyright owner" to "Copyright statment" or "More details about the copyrights" ?

**Comment by jcr** [comment]
I am closing this here. This is nothing of a technical bug/issue.
It belongs to the " Editorial domain "
