### ISSUE TITLE
Land Library Resource teaser view: logo organization should not only be data provider

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#105]
The teaser view for a LL resource on the front page shows the logo of the data provider. If there is no data provider, there is no logo. See the screenshot:

![screen shot 2016-08-11 at 11 47 04](https://cloud.githubusercontent.com/assets/6312043/17585062/fb857364-5fb9-11e6-8373-60a9107badb9.png)

Can we insert some sort of rule for that logo:
- If there is a data provider: logo data provider (we want to emphasize the importers)
- If there is no data provider: logo publisher (mandatory field, will always be there).
- If there is no logo publisher: then no logo on the teaser image.

**Comment by jcr** [comment]
this should become a teaser like we have on other parts of the site.
see #120
