### ISSUE TITLE
Link to Debate authors in Land Debate not functioning

### ISSUE THREAD

**Issue by lmeggiolaro** [landportal/drupal#106]
The automatic linking of debate facilitators in Land Debate is not working. It is not possible to add debate facilitators. When typing the name, no names appear.  This was working fine and stopped working for no apparent reason. It will negatively affect our credibility if not fixed immediately.

**Comment by dayures** [comment]
The error was "The view users is no longer eligible for the Facilitators field."
https://landportal.info/admin/reports/event/58616

The hot-fix solution was a change, using the admin UI, of ENTITY SELECTION.mode, from Views to Simple option.
https://landportal.info/admin/structure/types/manage/debate/fields/field_facilitators/field-settings

Maybe this link could help
https://www.drupal.org/node/2476457

**Comment by jcr** [comment]
this is fixed and rebaked in the landportal base module.
recently a debate was created and facilitators added without issues
