### ISSUE TITLE
Add background color to debate status block

### ISSUE THREAD

**Issue by dayures** [landportal/drupal#107]
Add background color in the debate status
http://landportal.info/debates/2015/10-24-december-online-discussion-women-and-family-farming-%E2%80%93-moving-forwards-iyff

Some helpul code code was added in commit https://github.com/landportal/drupal/commit/b679f8dda6db03237ddf86b43ef33ac3119c976e

**Comment by jcr** [comment]
the background color seems to be borken

**Comment by aostroverkhov** [comment]
@jcr that's done, please check on Beta (2.3.1 branch)

**Comment by jcr** [comment]
The colors are horrible and the text is barely visible.
Another things is, by hardcoding the templates (teaser) and removing all fields you though should not appear (like landvoc, facilitators, status) the overview page isn't as rich as before.

We will correct / review that in the next milestone by removing the theme template, re-enable the manage fields and having clean and proper CSS + global variables -for colors- .
