### ISSUE TITLE
Add “email” in the share it lateral buttons

### ISSUE THREAD

**Issue by dayures** [landportal/drupal#108]

**Comment by jcr** [comment]
new feat. Though it's probably very easy / quick todo I am bouncing that (again ...) to the next MS.
AFAIK it is only needed to:
- add a mail icon (?)
- edit the block to add mail link

**Comment by jcr** [comment]
it's there now! ;)
too bad it does open a new window and not a popup like the others.
I've looked a bit around about that- couldn't really find any info on how to either suppress this new window or at least turn it to a popup.
Strangely enough there is also code on our pages about a a2a modal.

Might also be worth noting that with add2any we load 3rd party script and pass on information to people we have no idea who they are or what they do with the data or user privacy. There website is just completely empty in that regard - nor do they say who they really are :D
