### ISSUE TITLE
Add possibility to add synonyms to Regions taxonomy

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#111]
We need the possibility to add synonyms to the Regions taxonomy for the different names used for countries.

**Comment by jcr** [comment]
done and commited yesterday (yes I was working at 9:30pm...)
https://github.com/landportal/drupal/commit/451137941d0228d356871b810bc119b6e81e2092
I also added synonyms and enabled translation to other taxonomies (like theme / overarch).

**Comment by lisettemeij** [comment]
Wonderful!

I created a filter for these Github messages, and now seem to be missing
them. Sorry about that ;-)

But great, I will start adding synonyms soon :)

Best,
Lisette


*Lisette Meij *| Land Portal Administration Officer & Librarian
Tel: +31 (0) 50 363 6065
Skype: lisettemeij
Website: www.landportal.info
