### ISSUE TITLE
Organizational profile - website field does not accept a certain type of URL (that does work)

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#112]
I was adding an organizational profile this morning and the website field did not accept the following URL:

https://naturalresources.wales/

I get an error that this is not a valid URL. But it works in my browser and couldn't find any other field.

Can we expand the permissions for this field to make sure that these URLs can be added as well?

**Comment by dayures** [comment]
It looks like the field doesn't like the ".wales" as first level domain

**Comment by lisettemeij** [comment]
Sure, I understood that that was the problem as well ;) But it is still an
actual working domain, so the field should accept it.

**Comment by dayures** [comment]
@jcr this issue is commented in this thread https://www.drupal.org/node/2299657

**Comment by jcr** [comment]
c8d562e should fix it

**Comment by dayures** [comment]
The issue re-appears with this URL
https://www.commonspace.scot/articles/9846/will-they-deliver-six-commissioners-proposed-advance-land-reform

**Comment by jcr** [comment]
settings wasn't right on the field_link.
It's now been updated to NOT validate the URLs for 'website' in : 
- organizations
- news
- events
- users profile
TODO: bake settings in ct_* features
