### ISSUE TITLE
News teaser - preview text should not include the different text styles (H1, H2, etc.)

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#113]
The teasers for the news shows the bigger text (H2) when it's in the description text. That should all be the same small text. See screenshot:

<img width="1280" alt="screen shot 2016-09-06 at 11 40 10" src="https://cloud.githubusercontent.com/assets/6312043/18269101/01e99bfa-7427-11e6-8e67-16fba4972915.png">

**Comment by aostroverkhov** [comment]
@jcr ready on Dev - https://dev.landportal.info/debate/news

**Comment by jcr** [comment]
not an ideal fix but I guess that'd do the job.
From what I saw - it forces all font size (p, h1, h2, h3 etc...) to be the same in this teaser.
