### ISSUE TITLE
Country Pages: The title for LGAF  block is missed

### ISSUE THREAD

**Issue by dayures** [landportal/drupal#115]
![lgaf-tittle-missed](https://cloud.githubusercontent.com/assets/1654811/18384568/90e16c32-768b-11e6-8e65-125991eafb17.png)

**Comment by jcr** [comment]
It should have "Land Governance Assessment Framework (LGAF)"
(translatable)

**Comment by aostroverkhov** [comment]
@jcr ready on Dev: https://dev.landportal.info/book/countries/VNM

**Comment by jcr** [comment]
yes - though it'll be a pain to change/translate this I guess this won't change often.

@aostroverkhov you really need to start updating the drupal doc (both dev and admin - for the LP team) to explain how those things get translated, text updated etc...
