### ISSUE TITLE
The "give us your feedback" button sends to a broken page

### ISSUE THREAD

**Issue by MarcelloLP** [landportal/drupal#118]
If you click on the "give us your feedback" button you get redirected here: http://landportal.info/contact-us

Yet this page is empty at the moment and shows the following:
Page not found
The requested page "/contact-us" could not be found.

A "mail to" link would work, at least initially

**Comment by jcr** [comment]
https://github.com/landportal/drupal/commit/78ee83af01969b3c25f53b1ce29928d88211e4c7
fixes the link

But... for other languages it sends you to the English version (link is /about/contact-us). Maybe add the lang prefix (if not 'en')  at the begining? (still hack-ish)

**Comment by MarcelloLP** [comment]
Nice, now it is working well, in english at least ;).

Many thanks,
Marcello

**Comment by aostroverkhov** [comment]
@jcr ok, will make it a proper link to correct translation, can we commit it to master branch?

**Comment by aostroverkhov** [comment]
@jcr fixed on Dev - https://dev.landportal.info/es/book/countries/VNM
