### ISSUE TITLE
Translated country names

### ISSUE THREAD

**Issue by jcr** [landportal/drupal#119]
in regions and countries taxonomy
make sure country terms have a translation

**Comment by jcr** [comment]
fixed on the production site. lp_taxonomy feature needs rebaking

**Comment by jcr** [comment]
Actually , Regions taxonomy is now translatable but the terms aren't translated.

**Comment by dayures** [comment]
fixed after run the translate_regions_importer 63332268ca452c586f83ea7b64d44da4a916ca00
