### ISSUE TITLE
Land Library resources translation

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#121]
Land Library resources should be translatable in Drupal.

**Comment by lisettemeij** [comment]
Sorry added this really quickly. Important elements to this are:
- All resources (all languages) need to show up regardless of the language interface (similar behaviour as 'language neutral';
- In the search form users should be able to filter out certain languages and that corresponds with the 'resource language'-field;
- Promoted items should only be promoted to the interface of their language ('resource language'-field).

Let me know if I am forgetting any elements to this.

**Comment by jcr** [comment]
As of now, LLR are translatable and behave the same as other nodes on the LP.
As discussed recently in a mail you got pretty spot on the point of how it works so i am no going to elaborate here.
To answer the last comment.

- [x]  All resources (all languages) need to show up regardless of the language interface (similar behaviour as 'language neutral';

This is indeed what lang. neutral is for. unless a resource is translated (and created in all the lang. we want it to appear) it'll show up everywhere. (this is, of course, independent of the actual language of the resource itself - we're talking about the node/entry in drupal)

- [ ] In the search form users should be able to filter out certain languages and that corresponds with the 'resource language'-field;

true; now that we're streamlining filter and references to taxonomy , it seems right to bring back this important filter to find out resource that are " in " a specific language.

- [ ] Promoted items should only be promoted to the interface of their language ('resource language'-field).

Land Library resources are now promotable in the same ways and at the same places than any other land portal content. Note that the LLR image should " fit " in such promoted header (which tends to go to full width slider).

**Comment by lisettemeij** [comment]
Thanks for this Jules.

But just to quickly clarify: the resources are translatable, but is the default setting of the node language still Language neutral? 

The node language field was hidden (placed in deprecated), because it was confusing for users to have two language fields to fill in (resource language, and language interface). 

If language neutral is still the default value, we need to think about how we are making the feature to translate resources more intuitive for users.

My proposal in this thread was to basically get rid of the language neutral feature and make sure that all content shows up in every interface (so behaving the same way as language neutral - and removing language neutral as an option altogether).

If that is not possible or not a good idea - how would you suggest to make the translation feature usable for users? 

Just thinking out loud here, could a solution be:

- Remove the node language field from the Deprecated tab and create a new tab 'translation' with this node language field in there;
- Put in enough text there / a link to a FAQ on how to add translations (we'll have to write that) explaining the language neutral feature, etc.

Do you think this is too complicated for the 'average' user and we should provide that option only to certain level users? (similar to organizational profiles, where the relationship with a partner, etc., can only be determined by LP users?)

**Comment by jcr** [comment]
Hi Lisette,

Sorry for the late late reply on this.
As you say, the language field is still set by default to "lang. neutral" so a resource by default can appear on all sites (en/fr/es/pt).
To translate it you indeed need to set it to something else than lang. neutral before being able to use the translation features and I agree the process might not be the most natural or intuitive.
As you suggest, backed up with a good explanation + clear interface that should be good enough.
Grouping language + translation options (AFIAK there is 1 field that let you flag if a content translation need revision).
Last I would suggest that yes, only our 'contributors' can have access to this (not simply registered users).
