### ISSUE TITLE
Print stylesheet

### ISSUE THREAD

**Issue by jcr** [landportal/drupal#122]
Have a working print style for the country page

PDF examples are available online for VNM, THA, etc...

**Comment by aostroverkhov** [comment]
@jcr ready on Beta - https://beta.landportal.info/book/countries/VNM

**Comment by jcr** [comment]
@aostroverkhov : we had a round of comments last Thus.
Essentially about : 

- pie chart / spider graph alignment (in 2 columns, the pie wasn't aligned properly)
- font size in general (to make them slightly smaller globally).
- Try to fit the indicators table in 1 page
- page breaks
_- to right logo size(?)_

what's the status on this? Can we close

**Comment by aostroverkhov** [comment]
@jcr sorry I thought this related to PDF version only, will update the print.css accordingly too.
item not quite clear though - "page breaks - to right logo size(?)" - could you please explain what's required here?

**Comment by aostroverkhov** [comment]
@jcr this is ready now, you can check on Dev

**Comment by jcr** [comment]
- "page breaks - to right logo size(?)"
there is a missing lines between the 2 elements
- page breaks: I can see is better , though in some case just before the map I have a whole white page

"to right logo size(?)" was a typo: read "toP right"

Other comments:
- the flag doesn't show up
- hide the compare countries and map forms (obviously)
- get compare chart and map on 1 page ideally.
