### ISSUE TITLE
Promoted slider

### ISSUE THREAD

**Issue by jcr** [landportal/drupal#123]
There is an issue with the layout of the image (I may have borken it?)
This is not documented in our drupal developer doc.

the view select 5 items? when we show only 3?
https://landportal.info/admin/structure/views/view/landbook_countries_related/edit/block_6?destination=book/countries/VNM

**Comment by aostroverkhov** [comment]
@jcr sorry could you please explain again what's exactly wrong? 3 items show on the screen but you can scroll the carousel to see 4th or 5th slides if they exist, like here for example - http://dev.landportal.info/book/countries/VNM

**Comment by lisettemeij** [comment]
Really really urgent!!! We are at a conference demonstrating the country pages..... This looks awful, so please fix ASAP!!

**Comment by lisettemeij** [comment]
It looks like this:
<img width="1280" alt="screen shot 2016-09-15 at 16 49 51" src="https://cloud.githubusercontent.com/assets/6312043/18567114/b137d06a-7b64-11e6-9cca-76625d564b03.png">

The 3 images should fill the whole width of the screen. As it was before.

**Comment by jcr** [comment]
nothing wrong, as discussed yesterday I wasn't sure why it was selecting more than 3.
on the live site the promoted items display strangely but this is fixed
