### ISSUE TITLE
Organizations lists

### ISSUE THREAD

**Issue by jcr** [landportal/drupal#124]
The display (view grid) overflow the page.
Change to something responsive which look about the same.

http://landportal.info/debate/community
http://landportal.info/organizations

**Comment by aostroverkhov** [comment]
@jcr fixed and uploaded to Dev:
http://dev.landportal.info/debate/community
http://dev.landportal.info/organizations

**Comment by jcr** [comment]
@aostroverkhov yesterday I had to "un-do" (remove file) the organizations_overview view that was duplicated in the code.
Please re-commit this view in the right place not creating duplicates.

**Comment by aostroverkhov** [comment]
@jcr sorry, committed a fix now.

**Comment by jcr** [comment]
seems ok now
