### ISSUE TITLE
Too many notices/error log

### ISSUE THREAD

**Issue by jcr** [landportal/drupal#125]
Review and clean dblog
https://landportal.info/admin/reports/dblog?page=1

There is a lot of
" Notice: Undefined property: stdClass::$region "
" Notice: Undefined property: stdClass::$title in ..." 
"Theme hook library_block not found (or other blocks)"
"Notice: Trying to get property of non-object in block_block_view() "

I bet most of those notices/errors comes from the new landbook related files / hooks.
Please review the code you wrote, be clean, logic, separate functionalities in modules / features.
Time to cleanup!

**Comment by jcr** [comment]
https://landportal.info/admin/reports/dblog

This is now producing sometimes up to 400 entries / min and is becoming really problematic.

Part of those messages I believe (may be wrong) are due to the wrong implementation of blocks in the country pages.
There are also lot of message related to add_to_any (?)

Few samples of issues to look at first:
(note that add_to_any is producing a fair share of the entries)
_from http://landportal.info/library/search?page=636&keyword=Food%20security.Livelihoods&f[0]=im_field_doc_type%3A3668_
> Notice: Trying to get property of non-object in addtoany_create_node_buttons() (line 284 of /etc/drupal/7/sites/all/modules/addtoany/addtoany.module).

_from http://beta.landportal.info/book/thematic/indigenous-community-land-rights_
> Notice: Undefined property: stdClass::$region in template_preprocess_block() (line 1037 of /usr/share/drupal7/modules/block/block.module).
> Notice: Undefined property: stdClass::$title in _block_render_blocks() (line 939 of /usr/share/drupal7/modules/block/block.module).


(same as above?)
_from http://landportal.info/pt/book/countries/KWT_
> Notice: Undefined property: stdClass::$region in template_preprocess_block() (line 1025 of /usr/share/drupal7/modules/block/block.module).
> Notice: Undefined property: stdClass::$region in template_preprocess_block() (line 1026 of /usr/share/drupal7/modules/block/block.module).

**Comment by jcr** [comment]
https://github.com/landportal/drupal/commit/494cf418078a10f6e0370438ca1f6e6f6fd076d5
should take care of numerous addtoany warning (hundred thousands per day!)
Next time you use a module read the doc!

**Comment by aostroverkhov** [comment]
@jcr this is ready, please check
