### ISSUE TITLE
The map fits half width instead the full width

### ISSUE THREAD

**Issue by dayures** [landportal/drupal#126]
![half map](https://cloud.githubusercontent.com/assets/1654811/18747286/c963c1d6-80cc-11e6-957a-2103ff0a7520.png)

https://landportal.info/book/countries/VNM

**Comment by jcr** [comment]
should be fixed by https://github.com/landportal/js-view-coda/commit/076d61c25ff25550282b1be3d185c56305fc1d1c
@webcodingstudio note that it will not print as nicely in PDF (visual adjustments still need to be made to the visualizations anyways)
