### ISSUE TITLE
Avoid the update messages for rdfx and rdf_indexer modules

### ISSUE THREAD

**Issue by dayures** [landportal/drupal#127]
This message appears in the modules update list https://landportal.info/admin/modules/update
MODULE - INSTALLED VERSION - RECOMMENDED VERSION
RDF Indexer (rdf_indexer) - 7.x-1.x-dev - 7.x-1.x-dev
RDF Extensions (rdfx) - 7.x-2.0-alpha4+9-dev     - 7.x-2.0-alpha4

We want to mantain the versions set in the landportal-custom.make file

**Comment by dayures** [comment]
as they look as unmaintained projects, and idea could be to fork them into our drupal and provide tags for the latests version of the repository (including patches)

**Comment by jcr** [comment]
This would be the worst possible scenario (fork them as abandoned project).
Both have been update recently (very recently in Drupal's world)
https://www.drupal.org/project/rdf_indexer , 7monhts ago
https://www.drupal.org/project/rdfx , < 1 year ago
The issues queue on rdf_indexer seems manageable (8), while the other have grown a bit more (close to a 100)
If we are going to 'fix them' and do serious work on this, the best is probably to contact the projects maintainers on Drupal and ask them to contribute directly upstream. Or provide patches that we put on drupal.org.


To resolve the original issue here , why don't we update the landportal-custom.make?
it currently 'pulls' : 
rdfx: 7.x-2.x from GIT
rdf_indexer: 7.x-1.x also from GIT

**Comment by dayures** [comment]
It is already configured to pull the latest version from git, but as far as it encounters a "new version" (a tag of a previous status), it updates to the old one.

And the latest commits for both projects are more than 2 years ago...

**Comment by dayures** [comment]
Forked projects in our github as repositories
https://github.com/landportal/rdf_indexer
https://github.com/landportal/rdfx

And created tags in order to fix this issue
