### ISSUE TITLE
PDF generation

### ISSUE THREAD

**Issue by jcr** [landportal/drupal#128]
For a, not statefull (doesn't follow user changes to vis.) PDF version on the CP.

FIX:
It seems that it doesn't work with all modules enabled.
On dev it seems about butI had to disable the addtoany (?) module to make it work.

What the status on this? I think this is of the last actions to close this milestone.

**Comment by aostroverkhov** [comment]
@jcr not seeing any issues on Dev now even with addtoany module enabled - https://dev.landportal.info/book/countries/VNM
Generated the attached PDF now without any issues:
[VNM.pdf](https://github.com/landportal/drupal/files/495226/VNM.pdf)

**Comment by jcr** [comment]
seems that it's working fine now.
Maybe one option to add now: 1cm margin on the bottom (wkhtmltopdf param).

later we will probably add a footer (with the footer-html option)
