### ISSUE TITLE
Missing image in landvoc (about OA categories and themes)

### ISSUE THREAD

**Issue by dayures** [landportal/drupal#132]
http://landportal.info/voc/landvoc

In the categorization section.

The image about themes and categories looks missed. I have checked the server and this image is not there.

**Comment by MarcelloLP** [comment]
Here it is the final version of the image. Also in drive/data/landvoc.
![oas and theme graphics_final](https://cloud.githubusercontent.com/assets/22029957/19077376/4efa1f36-8a44-11e6-8118-2b74ac6eb811.jpg)

**Comment by dayures** [comment]
![oa and themes](https://cloud.githubusercontent.com/assets/1654811/19080056/232461b6-8a56-11e6-8698-44f39185db1d.png)
