### ISSUE TITLE
Promoted to thematic pages

### ISSUE THREAD

**Issue by jcr** [landportal/drupal#134]
Same functionality as the country page

This provides a "promoted to thematic page" for Content types (news, blogposts, debates , events, organizations, library resources) in the publishing options box.
It will allow you to select (next to the promoted checkbox), on which thematic pages it will appear by selecting a thematic page (CT) OR adding theme and overarching category tags.

Also provide a 'promoted item' view for the Thematic pages (same as for the CP one)

This module should depend on the Thematic CT
Name should be something like: landbook_promoted_thematic
in : modules/landbook/(modules|feature)/promoted_thematic

**Comment by aostroverkhov** [comment]
@jcr this is ready, please check on Beta site.

**Comment by jcr** [comment]
done. one thing though,
in the promoted box,  it is showing the title of the thematic narrative which is in fact used as a subtitle.
The best solution would be to show the name of the Landvoc term it is linked to (under-specified when you had to develop it, I know...).

Question is, how difficult is it to use an entity reference filter for this field? should be easy no?
There is already a view for entityreference related to landvoc. The one used in the thematic narrative is at https://landportal.info/admin/structure/views/view/landvoc/edit/entityreference_1
as a very quick try I did such a reference filter at:
https://landportal.info/admin/structure/views/view/landvoc/edit/entityreference_2
It shows "Indigenous & Community Land Rights - (Themes) - Nid: 36381 "
(only one because there is no other thematic page right now)

**Comment by aostroverkhov** [comment]
@jcr this is ready, please check
