### ISSUE TITLE
Remove " Promoted to country page" display mode

### ISSUE THREAD

**Issue by jcr** [landportal/drupal#136]
AFAIK this is *only* used by the promoted/features view.
Unless this is really necessary, remove it.
It is confusing and doesn't (or shouldn't) change the way a node is displayed in the promoted/featured block which always show a picture at a specific size, the node title and link to it.
The way it display promoted items should be set at the view level (display: fields?) as we don't want it to change on any "promoted" block/slider.

**Comment by aostroverkhov** [comment]
@jcr yes it was unnecessary, removed it.

**Comment by jcr** [comment]
I think it was done. There should be a commit # to help close this ticket
