### ISSUE TITLE
Thematic related content

### ISSUE THREAD

**Issue by jcr** [landportal/drupal#140]
same view as for the Landbook country pages.

https://github.com/landportal/drupal/blob/master/modules/landbook/views/landbook_countries_related.inc

needs to pull content for either a Theme or a Overarching category (landvoc_to field)
likely related to
https://github.com/landportal/drupal/blob/master/modules/landbook/landbook.module#L81

**Comment by aostroverkhov** [comment]
@jcr this is ready, please check on Beta site.
