### ISSUE TITLE
Adapt country page style to thematic pages

### ISSUE THREAD

**Issue by jcr** [landportal/drupal#141]
The style doesn't adapt properly.

Beware of https://github.com/landportal/drupal/commit/f629fda97fd2880a3df7106759c1aa5da0a8ea80
Review the general grid implementation - specially the Country pages.

On the thematic pages:
- forms style is off
- titles don't have the right font / size / color (why isn't this general to .h1/h2/h3 classes ? / extend bootstrap classes properly!)

Make sure the media an related content style is also ok.

**Comment by aostroverkhov** [comment]
@jcr this is ready, please check on Beta site.
