### ISSUE TITLE
Remove the sentence "There is currently no content classified with this term" from indicator and dataset term view

### ISSUE THREAD

**Issue by dayures** [landportal/drupal#145]
For instance at http://landportal.info/book/indicator/wb-lgaf2016-651

![no-content-classified](https://cloud.githubusercontent.com/assets/1654811/19036316/66c7673e-896f-11e6-9297-7d79ccef86a7.png)

**Comment by jcr** [comment]
https://github.com/landportal/drupal-lpbs/commit/cb0812787cebe2dacc422144aa39ac9d28c9496a
