### ISSUE TITLE
Generate RDF for Link fields

### ISSUE THREAD

**Issue by dayures** [landportal/drupal#146]
Now, there is no RDF generated for these fields

For instance in the Taxonomy about LandVoc Concepts, the RDF from field AGROVOC URI ('field_agrovoc_uri') is not generated.

**Comment by dayures** [comment]
doc: https://www.drupal.org/node/1161910

**Comment by jcr** [comment]
this also needs to move to the more generic linked_uri (essentially for taxonomies?)
then we need to expose all those fields.

**Comment by dayures** [comment]
also happening in Taxonomy License, in the field "RDFLicense URI"

**Comment by dayures** [comment]
fixed in the project https://github.com/landportal/rdfx
