### ISSUE TITLE
LL Refine results menu on country page is suddenly not aligned next to the results anymore

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#147]
The Refine results menu for the Land Library on a country page is suddenly not aligned to the right of the Land Library results anymore. See attached screenshot.

<img width="1280" alt="screen shot 2016-10-06 at 09 59 05" src="https://cloud.githubusercontent.com/assets/6312043/19144792/cf92dd5a-8bab-11e6-9364-108b72fe2fcb.png">

Can this be aligned to the right again? 

Just some other comments about this part:
- Order of the previewed items: Currently it is "last added" to the LL if I'm not mistaken. I would like to see it order by publication date (with most recent first);
- The order of the resource types in the drop down menu is scrambled. First all the "child" categories show up, not under their "parent" categories. Can we fix that it's in the order of the actual taxonomy?
- A filter for 'publisher' would be very useful here;
- The dropdown menus ideally would only show the values for which there are results. Now too often, especially with the years, you get no results;

 - I would also probably like it better if the "find more resources" was under that refine menu, instead of under the previewed resources, so that it is more prominent

**Comment by jcr** [comment]
Fixed, end of last week I had to redo this view (related partners and library). The current implementation of the related media is confusing, not efficient and miss-implement some base Drupal concept leading to have all the related section disappeared end of last week.
The Media section is still using the old view (WebCoding one) and hooks I ask for over 2 months now that they are commented and explained (specially that they are useless in 90% case).
