### ISSUE TITLE
Alignment columns to the outer borders (blog post)

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#148]
Suddenly, the alignment of the two columns of a blog post went to the outer corners. I especially don't like the text being outlined to the right completely, as the social media sharing icons now block the text. See screenshot below:

![screen shot 2016-10-07 at 08 58 05](https://cloud.githubusercontent.com/assets/6312043/19181294/5ed4fc6c-8c6c-11e6-9ea2-6a0700e03c43.png)

Can we fix this to what it was before? (And why did this change again?)

**Comment by jcr** [comment]
#df9811b clean up block display. this should now render more 'properly' (and visible on dev at http://dev.landportal.info/blog-post/2016/10/why-womens-empowerment-must-start-land-rights)
