### ISSUE TITLE
Mobile view needs to be improved throughout the website

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#149]
Hi all,

I was looking at some updates in the Land Library on my phone this morning and noticed that the mobile view is really, really bad. At some point (perhaps with the redesign of the Land Debate) we need to go through each page of the website and fix the mobile views. See a couple of examples in the screenshots below:

![img_1494](https://cloud.githubusercontent.com/assets/6312043/19211850/bcd5c49c-8d46-11e6-9766-786314bfbc24.PNG)
![img_1493](https://cloud.githubusercontent.com/assets/6312043/19211852/bd1c6cc6-8d46-11e6-9270-c54146386833.PNG)
![img_1492](https://cloud.githubusercontent.com/assets/6312043/19211851/bd1b615a-8d46-11e6-930e-86ad23e30af4.PNG)

**Comment by jcr** [comment]
I am closing this for now (too broad / general).
In the meantime have a look at the new version as this have already been dramatically improved.
http://dev.landportal.info/library
http://dev.landportal.info/library/search/habitat
http://dev.landportal.info/library/resources/land-tenure-rights-need-greater-transparency-among-companies-worldwide/land-tenure
