### ISSUE TITLE
LandVoc and Regions tag displays on a Debate page

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#150]
Hi guys,

I realize this is something that will be addressed when we do the redesign of the Land Debate, but the tags are now appearing in a very ugly way on a page of an online discussion. See the screenshot below:

<img width="1280" alt="screen shot 2016-10-13 at 10 01 59" src="https://cloud.githubusercontent.com/assets/6312043/19341114/621609b0-912c-11e6-85f3-405ad6ee1a3d.png">

It's pushing away the general text and introduction of the debate. Can we, before this debate starts on the 23rd, move this back to the left? The tags should not be more prominent than the introduction to the debate in my opinion.

**Comment by jcr** [comment]
done
