### ISSUE TITLE
Flags in the LP

### ISSUE THREAD

**Issue by jcr** [landportal/drupal#152]
At the core of LP theme, implement flags
#110 , #109

Use a more global solution
https://github.com/gosquared/flags
MIT License - 2600 flags?

**Comment by dayures** [comment]
After a quick look to https://github.com/gosquared/flags
- The real number of "countries" supported are 263
- They use ISO2 codes (and the are some bugs)

There is also this project
https://github.com/stevenrskelton/flag-icon

**Comment by jcr** [comment]
done in the new theme

**Comment by dayures** [comment]
Some observations:
- There is a bug in the mapping. ISO2 code "AX" is ISO3 code "ALD"
- In the list provided by email, Curaçao was not included (ISO2:CW ISO3:CUW), and it should be included
- In the list provided by email, Sint Maarten was not included (ISO2:SX ISO3:SXM), and it should be included
- In the list provided by email, Bonaire, Sint Eustatius and Saba was not included (ISO2:BQ ISO3:BES), and it should be included

As a related task, a couple wrong countries will be removed

https://github.com/landportal/data/issues/1
https://github.com/landportal/data/issues/2

**Comment by jcr** [comment]
Quick recap on what is left TODO
- [ ] Missing ones (in regions taxonomy with iso code but missing), remove ?
  - Aland Islands

- [ ] Add missing css class:
  - flag-icon-cw
  - flag-icon-sx 
  - flag-icon-bq

- [ ] Add missing images flags for countries:
  - CUW : Curaçao
  - SXM : Sint Maarten
  - BES : Bonaire, Sint Eustatius and Saba

**Comment by dayures** [comment]
Aland Island ISO3 code is: ALA (no ALD)
