### ISSUE TITLE
Review grid based views

### ISSUE THREAD

**Issue by dayures** [landportal/drupal#155]
In https://landportal.info/book/countries the table of countries is not centered. As far as I haven't found a bootstrap native method to center a table (with a block is possible), I suggest to create an extension to bootstrap in order to fix this, and apply it on the countries table

.center-table {
    margin-left: auto;
    margin-right: auto;
}

Some doc at: http://stackoverflow.com/questions/34271236/centering-table-on-a-page-on-bootstrap

**Comment by jcr** [comment]
yes, saw that but no. 
The way we will do it in the new theme ( I put that here as a general explanation, can be applied to many more elements ) is by : letting the bootstrap theme do it's job.

For this specific case, it means change the view to display and un-formatted list (default).
Then either add the responsive / BS classes to the elements (view display option > do not add row / view classes > add col-sm-XX col-md-XX col-lg-XX) to the view OR override them in SCSS.
to keep responsivness, it should look something like:
.TARGETCLASS (here something like .view-row once it's in the right display format mode) {
 @extend .col-sm-XXX;
 @extend .col-md-XXX;
 @extend .col-lg-XXX;
....
}

this can be applied to most (all?) our grid listing including promoted stuff.

**Comment by jcr** [comment]
let's close that one and re-open specific tickets if needs be.
In general (responsive) grid display will be achieve by setting the list view mode to un-formatted and either because they're a know view and in CSS (like organization overviews / teasers) or by adding a 'grid' class to the view.
