### ISSUE TITLE
LL preview in organizational profiles - same resource showing up several times in result

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#157]
Hi,

In the Land Library resource previews of the organizational profiles, the same resource appears to be showing up several times in the preview, while the resource only exists once in the database. See below:

<img width="1280" alt="screen shot 2016-10-27 at 13 29 35" src="https://cloud.githubusercontent.com/assets/6312043/19765610/942b3c40-9c49-11e6-8e94-363f0c136ae4.png">

Why is this and can it be fixed?

**Comment by dayures** [comment]
After the first look, there is a problem with the pagination.
A hot fix as been applied 77c68f15f1926739715e330ae04a416048d15c8b

**Comment by jcr** [comment]
@dayures have this view been re-baked? can we close this issue?

**Comment by jcr** [comment]
thanks carlos
