### ISSUE TITLE
promoted content showing up in both English and French on the French page

### ISSUE THREAD

**Issue by lmeggiolaro** [landportal/drupal#158]
When content is translated in multiple languages, it shows up as duplicates on the French, Spanish and Portuguese versions of the website. Promoted content on the English page should only be promoted to the English page, not other languages.

**Comment by lisettemeij** [comment]
This is actually what I wanted to post now as well ;-) 

In the deprecated folder of the LLR form, there is a second language field, determining in which interface the resource shows up. The default is language neutral, meaning it shows up on all interfaces. If you promote the items to the front page, it shows up everywhere.

For French and Spanish, whenever those are promoted to the front page, I edit them so they don't show up on the English page. However, English ones are still showing up on French and Spanish.

We need to fix this. Is there a way that we can link the field together? If they resource language is set to English, the interface is automatically set to English as well?*

* There should probably be a second rule there that says *IF* there is a corresponding interface language (not an issue right now, but if we're adding more LLR in other languages than only EN, FR, ES and PT (and I think we should), this will become an issue.

**Comment by jcr** [comment]
OK I spent quite some time last week looking at it and 'fix' the actual landbook promoted view (as I discovered they were a total mess) - it should behave more as expected now(?)
In the new/next version this have been re-done (actually still work in progress but ),  the view / selection and display of content will now be the same base for all promoted view (which was asked from the beginning on but never done - instead our last contractor decided to spread related code all over the place).
