### ISSUE TITLE
Subtitle Thematic page + Definition Taxonomy Theme should be the same thing

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#160]
We decided in a call about the thematic pages today that the captions that Nicholas wrote for the first  5 thematic pages, should be the same as the definitions for the themes in the current taxonomy.

Some of the descriptions added to the theme taxonomies sometimes are long now, but those were added before the thematic pages were there and to full up the space basically. We now know that we want those captions that we'll have for every theme, to be the definitions of the themes in the taxonomy.

So, can we somehow link these fields together? To make sure we don't have to change in 2 places every time we want to change a definition slightly? Thanks :)

**Comment by jcr** [comment]
we had that discussion last week with Carlos and Marcello and actually concluded that not based on the exact same argument you have for it ;)))

The main reason for the opposite choice being:
narrative (like the one for countries) aren't a definition for the term it is really a narrative. Imagine when we push our theme and OA to landvoc for instance. the definition there should be the one we have in the taxonomy term (more generic) not the narrative.

The narrative should be about story telling , not a definition. The way it is right now it also more flexible. What is true is that some text we added in the term definition (when narratives weren't there) should be move to a narrative.

**Comment by lisettemeij** [comment]
Ok, I think you misunderstood me. I'm not talking about the narrative here, I'm talking about the CAPTION that should be the same as the definition. The narrative is the longer description that goes in the 'description' field of the thematic page, not the 'subtitle' field.

Nicholas made the captions for the 5 first themes already: https://docs.google.com/document/d/1ro8MwkaUc6i-fd_2TetEUq5bKAWHjEvgUPsHjcW62zE/edit

We agreed today that these should be both the definitions and the captions and should be only changeable in one place on the website (Marcello was part of that call as well and agreed).

**Comment by jcr** [comment]
done, need styling for the TP

**Comment by dayures** [comment]
Agreements:
- The editable definition (also called description) of a theme will be placed in the taxonomy term (theme) definition.
- This theme definition will be also shown at the top of ALL thematic narratives of a theme.
- 5 theme definitions will be edited, and changed using the Nicholas captions
- The title of a thematic narrative will not be shown anywhere.

**Comment by jcr** [comment]
fixed, also have the internal nav back (which works with translate-able content)
