### ISSUE TITLE
URLs not accepted in URL field (raised this before - seems to be closed but still issue)

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#161]
This URL is not accepted again: https://www.commonspace.scot/articles/9846/will-they-deliver-six-commissioners-proposed-advance-land-reform

I've raised this issue before, don't see it here anymore so I guess someone closed it without it being actually fixed.

**Comment by jcr** [comment]
if you don't tell me where it's not going to be fixed....

**Comment by lisettemeij** [comment]
It is everywhere, in all URL fields. The previous bug with the exact same problem I described in thorough detail. Then it was a URL field in an organizational profile, this time it was a news item. I am not going to repeat every bug that I report after it's been (unjustly apparently) deleted. 

I am showing you the kind of URL the fields reject, and since it's apparently in every content type where we add a URL, it is a general behavior and it needs to be generally fixed.

**Comment by dayures** [comment]
Duplicate. Move interesting content to #112
