### ISSUE TITLE
all the anchors in the thematic narrative have the same anchor-id

### ISSUE THREAD

**Issue by dayures** [landportal/drupal#163]
As you can see in http://landportal.info/book/thematic/indigenous-community-land-rights
all the blocks in the narrative links to #legalinfo

**Comment by jcr** [comment]
looks like a )#($^ bug from people who hardcode stuff and don't know HTML or coding 101.
(see landportal/templates/field-collection-item--field_country_info.tpl.php)
We can't see it right now (don't know why it's more broken than last week), but this is already fixed on the new version (by simply not having hardcoded templates and let things render like they should)
