### ISSUE TITLE
English promoted news promoted to French, Spanish and Portuguese

### ISSUE THREAD

**Issue by lmeggiolaro** [landportal/drupal#165]
When English news is promoted, it is also promoted to the French, Spanish and Portuguese versions of the site, overriding all French, Spanish and Portuguese promoted news. This should not be the case. English news that is promoted should only appear on the English homepage.

**Comment by jcr** [comment]
yes, when there is no translation for a promoted item, the default behavior was to show the one we have (language neutral).
I have now changed them to only show in the user's selected language. If something isn't translated it will now not show up.
(I cannot remember how and if that decision was made or debated in the past but it haven't changed on months - or even more than a year)
