### ISSUE TITLE
Land Portal is showing up as Landportal in Google search results

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#166]
I don't know where this is managed, but when you search for a publication for example on Google and see the Land Portal in the search result, it says "[title of the resource] | Landportal"

Carlos mentioned that this can be changed here: https://landportal.info/admin/config/system/site-information

It should be Land Portal --> Everywhere, Landportal should be deleted wherever it says.

**Comment by jcr** [comment]
This one have been updated now.
It's hard to track all the places this could be but we will (I actually) work on getting better SEO basics onto the site as early as next year probably.
(including better titles, desciption, keywords meta and other basic voodoo things search bots likes)
