### ISSUE TITLE
URI Mismatch, not forcing https

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#169]
Unable to login to the Land Portal from http, forced switch to https appears not to be working.

https://lh3.googleusercontent.com/-4lISGFkYadE/WDf2DEBY14I/AAAAAAAAAV4/uVwEDPYh9Jswq0_jK0fXd0gVdqiXYnRmACL0B/h728/2016-11-25.png

**Comment by jcr** [comment]
fixed
