### ISSUE TITLE
Drupal created an alias for users when changing mailchimp subscription status

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#172]
I discovered that I could batch change Land Portal user information in Drupal, including whether or not users are subscribed to the newsletter. I had realized it was a problem, and that perhaps a great many people were not subscribed to the newsletter. I batch subscribed all those marked as using the English interface as a subscribed to the English newsletter (presumably connected to mailchimp). This seemed to be working, but when finished, I said it created an alias for each user with a -0 at the end. I don't see any reason why an alias would need to be created for everyone simply because we were updated a subscription preference. This is the bug, as now apparently we have nearly 1000 uneccessary aliases for Land Portal users.

**Comment by jcr** [comment]
for the record there was 39 aliases involved.
It have been cleanup
