### ISSUE TITLE
Blogs still screwed up looking

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#174]
All the text on blogs is forced to the right side of the page.

![image](https://cloud.githubusercontent.com/assets/23736268/20718551/6177ead0-b659-11e6-838e-fc1e52110e94.png)

**Comment by jcr** [comment]
(will) work on dev.

**Comment by realneilsorensen** [comment]
How can it be closed if it's not resolved? Please leave issues open until they are actually resolved.

**Comment by jcr** [comment]
this is how it looks today : https://dev.landportal.info/blog-post/2016/11/ground-multi-functionality-land

I closed this in order to know what is done and / or not . It is of course with the assumption that it work for the next release
