### ISSUE TITLE
Land Library featured resources show old resources

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#176]
Hi,

The featured resources on the LL landing page are all old resources. Has the filter changed?

Can we change it back to the most recent ones that have been promoted to front page?

Thanks,

Lisette

**Comment by jcr** [comment]
Yes, sorry about that, probably a side effect of when I updated the promoted slider recently.
Laura was asking to remove English content from the promoted / featured thing for other languages.
I only tilt yesterday that this was probably going to create issues for the library.
I think a still ongoing issue is that there is no library resource that will currently be visible on the other promoted slider (to be checked).
This should go away with the new version where the promoted thingy is now a proper / clean centralize module and not peaces of code all around the place (thanks again to our external contractors - <3 loosing days redoing work already paid for). This ways rather that updating filters and things in 4 different places there is now 1.
