### ISSUE TITLE
Add a drupal module to check if a Resource URL of a LLR is alive (2xx, 3xx)

### ISSUE THREAD

**Issue by dayures** [landportal/drupal#177]

**Comment by dayures** [comment]
Maybe this could be the module
https://www.drupal.org/project/linkchecker

@jcr what do you think? I tested in my instance and worked fine.

**Comment by jcr** [comment]
yes only thing to make sure is that it doesn't go 'crazy' when we run it on the portal (given the number of nodes + fields) and that there are few options to control this plugin 'crawls' as it seems to be running on it's own.
From what I see it mostly is made to scan body-like fields (with probably some options for link-type fields), which would also be a good thing to have anyways (on pages to check that our internal links are correct or other content types...)

**Comment by dayures** [comment]
In my instance, the crawl was done smoothly. As far as I have reviewed, it also checks links fields.

**Comment by dayures** [comment]
For the records, the linkchecker module needs to be customized:
 -select internal-external links to check
- select the non-error HTTP codes
- select the CT to be scanned
