### ISSUE TITLE
Land Portal no longer connected to Mailchimp at all

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#178]
The Land Portal seems to be no longer connected to Mailchimp at all. I am unable to assign new members to subscription lists, even the possibility to do so has completely and suddenly disappeared. What is going on? This is a nightmare.

![image](https://cloud.githubusercontent.com/assets/23736268/21217370/21d07c76-c2ac-11e6-9faf-55318122446d.png)

**Comment by jcr** [comment]
The " nightmare " should be over. Carlos updated some modules on the LP main server yesterday and things haven't actually gone so smoothly + I also applied some (3) pending, critical, security-related updates.
It now seems to work correctly
