### ISSUE TITLE
Create all thematic pages (unpublished) in order to be able to promote content

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#182]
Hi,

Can we create all the thematic pages that are currently not online? Then we can already start promoting content to it, so it's all ready when we launch the pages.

We currently have:
- Forest Tenure
- Land & Gender
- Indigenous & Community Land Rights
- Commercial Pressures on land (unpublished) -> To be Land Investments
- Urban Tenure (unpublished)

What we still need:
- Land & Food Security
- Land Stakeholders & Institutions
- Land, Climate Change & Environment
- Land Conflicts
- Rangelands, Drylands & Pastoralism

Thanks!

Lisette

**Comment by jcr** [comment]
Created https://landportal.info/admin/content?type[0]=thematic_narrative 
As spotted yesterday there is a bug making it not possible to promote other content to it as they are no published (too many 'published' filters). - fixed by commit #d600e54
