### ISSUE TITLE
Add Author + Publication date to News CT

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#183]
Hi,

To address what we've all already discussed, we need to add two fields that are always posted in News description field, that should be two separate fields:
- Author (free text field)
- Publication date

I would also make the publication date maybe free text field? Usually I can add date+month+year for a news article, but just in case that's not possible for some people..?

I'll let you guys decide :)

I also think we should add "Source" in the display to the top (above description) but that's a different thing and probably will be addressed with the redesign of the Land Debate.

**Comment by dayures** [comment]
- Add these fields in the teaser view
- Not show the node publication date in the teaser
![captura3](https://cloud.githubusercontent.com/assets/1654811/21891355/983684dc-d8d2-11e6-8c16-859a7a2bc2c3.PNG)

**Comment by dayures** [comment]
Change the website Links field to source. TBD

**Comment by jcr** [comment]
For the record, the news CT have been update with those fields as well as the page full display.
We still need to show (eventually) those fields in the teaser view (or other) but this will likely be done with the re-design integration. For now it show the publication date (not authoring sorry).
