### ISSUE TITLE
Occupied Territories of Palestine not in Country Taxonomy

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#185]
Palestine / Occupied Territories of Palestine is not in the country taxonomy. We have a country narrative for Palestine, but cannot add it.

**Comment by dayures** [comment]
@jcr should we use the "regions" taxonomy ?

**Comment by jcr** [comment]
yes, same for #186 .

**Comment by jcr** [comment]
ain regions taxonomy (FYI Countries isn't used and is as of now officially deprecated)
