### ISSUE TITLE
No Country Taxonomy for Kosovo

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#186]
We have a narrative for Kosovo, but it is not included in the country taxonomy.

**Comment by jcr** [comment]
ain regions taxonomy (FYI Countries isn't used and is as of now officially deprecated)

**Comment by dayures** [comment]
Just to take into account that Kosovo has NOT an ISO3 code (yet).
The ISO 2 code XK is being used by the European Commission, Switzerland, the Deutsche Bundesbank, SWIFT, and other organizations as a temporary country code for Kosovo.
