### ISSUE TITLE
Cannot add translations of country narratives in the Land Book

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#187]
The possibility of adding translations of country narratives in multiple languages in the Land Book is not activated. This is urgent, as we have several country narratives delivered in Spanish, and will have more in other languages in the future.

This also means we need to be prepared and able to have French, Spanish, and Portuguese translations of all the elements of the Land Book, including the visualizations, news, blogs, etc.

**Comment by jcr** [comment]
This 'fix' / capability will come in the new release - so available by end of this week.
It is already working on the new version, as visible on dev:
https://dev.landportal.info/node/38686/translate

Note that to translate a narrative you need to:
1. edit the existing one (if any), set it to English and save.
2. THEN you will have the translate button next to the view/edit/revisions controls menus on the top right (next to the title)
