### ISSUE TITLE
RDF module errors on drupal admin forms

### ISSUE THREAD

**Issue by jcr** [landportal/drupal#188]
It seems that the RDF module is creating an error when saving *some* settings from the admin.

"The website encountered an unexpected error. Please try again later."
Error message is:

> PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'bundle' cannot be null: INSERT INTO {rdf_mapping} (type, bundle, mapping) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2); Array ( [:db_insert_placeholder_0] => node [:db_insert_placeholder_1] => [:db_insert_placeholder_2] => a:9:{s:7:"rdftype";a:2:{i:0;s:9:"sioc:Item";i:1;s:13:"foaf:Document";}s:5:"title";a:2:{s:10:"predicates";a:1:{i:0;s:8:"dc:title";}s:4:"type";s:8:"property";}s:7:"created";a:3:{s:10:"predicates";a:2:{i:0;s:7:"dc:date";i:1;s:10:"dc:created";}s:8:"datatype";s:12:"xsd:dateTime";s:8:"callback";s:12:"date_iso8601";}s:7:"changed";a:3:{s:10:"predicates";a:1:{i:0;s:11:"dc:modified";}s:8:"datatype";s:12:"xsd:dateTime";s:8:"callback";s:12:"date_iso8601";}s:4:"body";a:1:{s:10:"predicates";a:1:{i:0;s:15:"content:encoded";}}s:3:"uid";a:2:{s:10:"predicates";a:1:{i:0;s:16:"sioc:has_creator";}s:4:"type";s:3:"rel";}s:4:"name";a:1:{s:10:"predicates";a:1:{i:0;s:9:"foaf:name";}}s:13:"comment_count";a:2:{s:10:"predicates";a:1:{i:0;s:16:"sioc:num_replies";}s:8:"datatype";s:11:"xsd:integer";}s:13:"last_activity";a:3:{s:10:"predicates";a:1:{i:0;s:23:"sioc:last_activity_date";}s:8:"datatype";s:12:"xsd:dateTime";s:8:"callback";s:12:"date_iso8601";}} ) in rdf_mapping_save() (line 255 of /usr/share/drupal7/modules/rdf/rdf.module).

**Comment by jcr** [comment]
@dayures was this sort of error related to NS conflicts?

**Comment by dayures** [comment]
Shouldn't be. But it is possible.

Please, next time this issue appear, provide more context about it (the action that raised that error)

**Comment by dayures** [comment]
Doc for the future, if it is needed https://www.drupal.org/node/2457795

**Comment by dayures** [comment]
Commit landportal/rdfx@8de4b30302f786b0a7630472ac87662435f3eb9a probably will help to close definitely this issue (from https://www.drupal.org/node/1271498)
