### ISSUE TITLE
Header menus not responsive

### ISSUE THREAD

**Issue by jcr** [landportal/drupal#19]
The header menu  block (for debates / library / book) aren't responsive anymore.

the menu items should fold in 2 lines for medium screen / be hidden for small devices?
use bootstrap nav bar: http://getbootstrap.com/components/#navbar

**Comment by aostroverkhov** [comment]
@jcr already started working on the menus in the new country pages, https://dev.landportal.info/book/countries/FRA
Or should we still fix it separately and commit to master before the new country pages?

**Comment by jcr** [comment]
yes this is now working the same way bootstrap menus folds by default on small devices.
