### ISSUE TITLE
Blogs not getting picked up in search engines / google

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#191]
I have flagged this before, but the blogs are not getting picked up by google/other search engines.

Search any blog that was posted on another website and you will see.

This blog for example: https://landportal.info/blog-post/2016/06/land-tenure-what-have-we-learned-four-years-after-approving-set-international-land

We posted in June, it doesn't even come up in the search results. It should be the second or third result on google if you search the exact title, but it doesn't come up at all. This is a serious issue that is reducing organic traffic to the Land Portal.

**Comment by jcr** [comment]
ACK. I will deal with improving search and related after the next MS.
FYI the new version is also going to bring much improvements on this side but there are also a couple of other things to note here.

1/ your statement is false. Search engines are crawling this content and it is referenced (I invite you to do a search scoped on landportal.info and check for yourself).

2/ about 2/3 (maybe even 3/4) of the work to get our website rank climb up in search engines is actually done outside of the site itself.
For the most part by creating a network of healthy links, articles, websites that point to OUR site, articles and resource. One question arise, how much have you lobbied to our partners, organizations, supporters, individuals we work with to have external links pointing to us? This is the very basics of referencing (and have been for the past 10 years or so - this is no secret) - for our site/domain to gain weight. We need solid links from external source to our site and by that I mean something like hundreds of them to start having any credibility for search ranking.

A simple example about this blog post. It was originally posted / cross-posted on WB site and, as you can see in the google results there are other pages linking to it but none point to landportal.info...
My point being that we clearly don't have enough "weight" to even hope being on the first result page for now (unless we search for a very specific thing that we are almost the only one to have).

The ball is in your hands as much as mines (or even more ;).

**Comment by jcr** [comment]
Closing this.
1/ google and search engines are (always were) indexing our content (all of it) under Debate, including blogs
2/ doing a search now on Land + Timby, we get the 1st position on search result for a blog posted 2 weeks ago. Also first page (6th pos) on land + aiddata. Those are the 2 most recent blogs
