### ISSUE TITLE
Display issue with indicators (images/text overlap)

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#192]
Hi, see the screenshot below:

<img width="1280" alt="screen shot 2017-01-05 at 14 04 17" src="https://cloud.githubusercontent.com/assets/6312043/21681547/f2d9d08e-d34f-11e6-9554-53698c4d5780.png">

As you can see, the number of the country is overlapping with the country name. Can we fix this?

**Comment by jcr** [comment]
yes, I don't know why it's also borken in production.
Marcello pointed it on the release doc as well

it's fixed and visible on beta & dev
