### ISSUE TITLE
Add text in the footer (Address, Bank account, etc.)

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#193]
We should add the placeholder text in the footer, such as:
- Address of the Foundation
- Our hello@landportal.info email address
- Bank account number (perhaps with link to donate page)
- Etc.

**Comment by jcr** [comment]
fixed, see on https://stage.landportal.info/about
to enable in production, edit the block text, and set the visibility to "All pages except those listed"
https://stage.landportal.info/admin/structure/block/manage/landportal_blocks/landportal_footer/configure
