### ISSUE TITLE
Mailing List / Mailchimp not connected to user registration

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#194]
Mail chimp and the mailing lists still are not connected to user registration. This is a problem.

![image](https://cloud.githubusercontent.com/assets/23736268/21713596/f9c2a2bc-d3fa-11e6-9655-419b31d3371d.png)

**Comment by jcr** [comment]
OK turns out that when the last LL importers have been deployed something have reverted a the MC module and library to a former version creating this issue I had actually dealt with last month.
I will look again at that once the new version is live to make sure it works

**Comment by jcr** [comment]
ah forgot to mention it's already been (hot fixed on the main/live site.

**Comment by jcr** [comment]
checked with a user who registered recently (2d ago) he is on the MC lists.
All seems fine.
For the record, With the new version of MC plugins user accounts now have a 'real' MC fields (one per NL).

@realneilsorensen : On the MC side there is a real need to cleanup un-used elements in
 - Campaigns https://us2.admin.mailchimp.com/campaigns/ 
 - Templates  https://us2.admin.mailchimp.com/templates/
 - and maybe also Lists https://us2.admin.mailchimp.com/lists/

It makes it confusing and prone to errors in selecting groups, sending messages and so on. Plus any implementation of User/Group delegated lists we might (re)do in Drupal will probably reflect this.
Last point ; last time I checked we will need to re-create proper dynamic templates on MC for Drupal to understand which section can be filled of variable used. Good news is some basic features like putting images or even inserting(?) node teaser seemed to work (very quick tests I run few months ago).
