### ISSUE TITLE
Use advanced select on landvoc terms in admin form

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#195]
The 'related concepts' field for adding Land Portal users still uses the scroll down menu with having to press ctrl to be able to add multiple fields, which many people do not know how to do. 

This should be the same as the related terms / LandVoc terms for news, publications, blogs, the Land Library, etc. Please switch it.

Thanks,

![image](https://cloud.githubusercontent.com/assets/23736268/21761209/aa3ab0c8-d651-11e6-97ef-091fc5119baa.png)

**Comment by jcr** [comment]
Done, it will be live in the next release (already visible on stage).
Also note that currently, on the 'public' register form the select/tag are already working.

The fix (see issue 200) is even broader than just the admin user. It should now work on most admin forms (may still need fine tuning).
See also https://github.com/landportal/drupal/issues/200
