### ISSUE TITLE
Need to be able to have different images in language translations for news, blogs, debates, etc.

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#196]
It is not possible to associate a different image with a translation of a node. It is only possible to associate a single image with all node translations. As indicated in numerous occasions over the past year, this is a problem, as we often have graphics that include text, for debates and elsewhere, infographics, etc. We need to be able to have an image associate with each translation. I know this is simple and possible, so please adjust Drupal asap to accommodate this request.

![forum conflitos eng - canva ok](https://cloud.githubusercontent.com/assets/23736268/21765023/90a02cb4-d666-11e6-982c-30ff372a4d9b.png)
![forum conflitos por - canva ok](https://cloud.githubusercontent.com/assets/23736268/21765024/90a387ba-d666-11e6-8aa0-d52255c52894.png)
![forum conflitos spa - canva ok](https://cloud.githubusercontent.com/assets/23736268/21765025/90a5aedc-d666-11e6-84c5-6a9242d7bd0e.png)

**Comment by jcr** [comment]
As discussed a few days ago , we agree that there is a legitimate use for this type of images but it is not the ones we should use for the 'preview' or illustration of the content.
The image / thumbnail should be text-less and wide screen friendly. This should be explained and implemented  with site design work.

To use / have those images with text in multiple languages , we need to upload them via the media library and link them where needed.
