### ISSUE TITLE
Duplicate promoted item on front page

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#198]
Although it is only promoted once and it appears to be the same link, this article appears twice as a promoted article on the front page:

https://landportal.info/blog-post/2017/01/fair-treatment-property-rights

**Comment by jcr** [comment]
fixed, there was actually 2 items
http://landportal.info/node/38995/edit
and
http://landportal.info/node/38994/edit
I unpublished, unpromoted, changed the path of the later one
