### ISSUE TITLE
Show the "leaf" icon for OA, Themes and LandVoc concepts

### ISSUE THREAD

**Issue by dayures** [landportal/drupal#199]
![captura-2](https://cloud.githubusercontent.com/assets/1654811/21891249/01082a02-d8d2-11e6-9ec8-8b4458ad1ad5.PNG)

This issue appears in some places in the website, for instance:
http://landportal.info/book/catalog
http://landportal.info/book/thematic/forest-tenure

**Comment by jcr** [comment]
the thing is , this icon only show up in front of OA. So if a node only have theme and concepts it won't show.
Now, most (every?) node that display landvoc stuff (OA + Themes + concepts) should be "grouped" together and this leaf icon should decorate the group  not only the OA.

have fun rebuilding all displays, for all CT...

**Comment by jcr** [comment]
this is all commited in the partners branch.
all CT and display modes now wrap Categories + themes + concepts in a 'landvoc'  div/group
also added/cleaned CSS accordingly
