### ISSUE TITLE
Bootstrap select

### ISSUE THREAD

**Issue by dayures** [landportal/drupal#200]
- [x] View filters select
- [ ] Vizz LB country pages (countries and indicators)
- [x] Admin forms LB admin settings
- [x] Admin form create LLR

**Comment by jcr** [comment]
*almost* done.
https://github.com/landportal/drupal/commit/f1424b5f8bbe6ce0a48109665a361974865854bc
https://github.com/landportal/drupal/commit/00aa61aa46deeec5bd28372326df99d20292fedc

Only LB viz. form aren't working yet as there is no Drupal hooks on those forms.
Solution could be to attach the JS select2 behaviors simply on viz. blocks that needs them.
