### ISSUE TITLE
Pagination is not working in the thematic pages for LLR resources block

### ISSUE THREAD

**Issue by dayures** [landportal/drupal#203]
http://landportal.info/book/thematic/indigenous-community-land-rights

**Comment by jcr** [comment]
For the record - I think this should be more general.
Library related-content (for thematics, country, organization) should have a more consistent display.
We need to show how much total resources there is (done), maybe the pager (also done, for both thematic and CP) but we really need to have a "find more on the library" link that point you to a "browse" page with all this content.
