### ISSUE TITLE
Too complicated to put geographical focus and related terms in new release

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#207]
It's difficult to put the geographical focus and related terms in the new release. You have to type in each term separately and hope it is in the system, and then you have to delete the term before entering another one. It is not intuitive and will be confusing for users. 
![image](https://cloud.githubusercontent.com/assets/23736268/22014317/682d7a42-dc9d-11e6-9118-23984fe2bd46.png)

**Comment by realneilsorensen** [comment]
Also, after entering an overarching theme/themes, they don't disappear.

**Comment by jcr** [comment]
right now we using globally https://silviomoreto.github.io/bootstrap-select/
maybe we should switch to something like https://select2.github.io/

**Comment by lisettemeij** [comment]
I see that I entered this without noticing that it was already put in. Can we please make this a priority? This is a huge frustration when you want to add something, and that it really bad for users.

I don't know what you suggested to switch to, but I would suggest to simply have it as we had before. 

Anyway: please make it a priority!

**Comment by jcr** [comment]
switched to new select.

FYI the reason it was switched is mainly because before we had 2 drupal modules + 3 JS libraries to do that when now we only have 1 to do the job.
