### ISSUE TITLE
Search feature on Land Portal is "temporarily unavailable"

### ISSUE THREAD

**Issue by ntagliar** [landportal/drupal#209]
I'm just making sure you are aware of this
<img width="1280" alt="screen shot 2017-01-18 at 11 10 13 am" src="https://cloud.githubusercontent.com/assets/24232810/22059845/d2ad1a4a-dd6e-11e6-98aa-ffcf47083804.png">

**Comment by jcr** [comment]
yes it have crashed yesterday...but this is no drupal error to fix
