### ISSUE TITLE
Issue with form entries (autocomplete) since new release

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#211]
The autocomplete form entries in the new release are working less good than they were before:

- When typing one concept and then wanting to add another, you have to first delete the typed word to get to a new one. Because other than before, when a word is selected the text does not get deleted, see below:
![screen shot 2017-01-18 at 13 56 35](https://cloud.githubusercontent.com/assets/6312043/22064916/fe4bc2ac-dd85-11e6-8f80-00313feace6d.png)
I would like to see that back to concept selected -> text deleted. So you can easily move on to the next concept.

- To delete one that you entered by mistake is a bit annoying as well. For example the image below, I will have to enter something close to "land alliance" again, to be able to untick one of these in the list.
![screen shot 2017-01-18 at 13 57 50](https://cloud.githubusercontent.com/assets/6312043/22064950/2bdd6400-dd86-11e6-8376-f1422315a646.png)
I would like to see that back to how it was before, that you can simply click on the name (or hit backspace) to delete an entry that wasn't needed after all.

**Comment by jcr** [comment]
see also #207 , will try to address this quickly. In the meantime I already have make 2 small adjustments to make it less worth.
closing this ticket, follow-up on #207
