### ISSUE TITLE
Add new LLR form. A couple of improvements

### ISSUE THREAD

**Issue by dayures** [landportal/drupal#212]
- The subtitle looks really prominent (maybe too much).
![sub](https://cloud.githubusercontent.com/assets/1654811/22065199/6e19c98e-dd87-11e6-8f23-878c6d16e1d8.PNG)

- There is an issue with the display of the list of Resource types
![rt](https://cloud.githubusercontent.com/assets/1654811/22065202/757be0a4-dd87-11e6-868c-614112036c0b.PNG)

@lisettemeij Added here to be informed

**Comment by jcr** [comment]
Not relevant anymore I believe
