### ISSUE TITLE
Display issue with Debate comments

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#214]
There is an issue with the Debate comments. This is important, because we're launching a new discussion this week and it needs to look good!!

See below:
<img width="1280" alt="screen shot 2017-01-23 at 09 10 41" src="https://cloud.githubusercontent.com/assets/6312043/22196398/524f6690-e14d-11e6-8bd0-6345159867d5.png">

**Comment by jcr** [comment]
this have also been fixed this morning, check and re-open if you still see some issues.
The one _small_ bug I still see is for smaller screen there is a Y-axis scroll to fix (leaving this issue open for now)

**Comment by jcr** [comment]
last little layout bug closed by commit  6e4036d in theme (will be pulled in prod shortly)
