### ISSUE TITLE
Promoting items to thematic pages problematic

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#217]
The system for promoting items to thematic pages, which was fine before the major update of the Land Portal, is much worse and not very understandable for selecting the thematic page. 

Please revert to the system that was in place before.

![image](https://cloud.githubusercontent.com/assets/23736268/22239756/41034980-e218-11e6-8ae6-f78efaec644e.png)

**Comment by realneilsorensen** [comment]
Also, the permissions are no longer functioning, and people with contributor status are unable to publish blogs (or they no longer understand it, which is also possible because it is very different than before.).

**Comment by jcr** [comment]
promoted by thematic now show the theme term, not the narrative title.
the permission thing you're mentioning is another story. While I had a go at trying to improve and fix it while re-doing the roles back few weeks ago, there is still some 'issues' according to the workflow we discussed in Roma back in Sept. I will have a look at it again shortly - to make sure contributors content get published directly.
