### ISSUE TITLE
LLR form + display adjustments with subtitles

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#219]
The LLR form is not ideal yet with adding subtitles:

Can we please remove the green background here and there is no need for several subtitles to be entered. Just one is fine. Never seen an instance where I needed more.

<img width="1280" alt="screen shot 2017-01-24 at 10 47 18" src="https://cloud.githubusercontent.com/assets/6312043/22242171/aaa17fc4-e222-11e6-8374-3e3efd3f2aa8.png">

It also needs to be adjusted in the view. It should not be green and should be aligned the same as the title, perhaps slightly smaller and lighter and below the title. It should not affect where the abstract is placed.

<img width="1280" alt="screen shot 2017-01-24 at 10 47 09" src="https://cloud.githubusercontent.com/assets/6312043/22242153/996ba374-e222-11e6-9507-cb27badbd1e8.png">

**Comment by lisettemeij** [comment]
Got a comment from Terry (MRLG) as well that this green title looks awful.

They're paying us to get LL resources online, so we need to change the color of this subtitle. No idea why that suddenly turned green.

Just emphasizing the urgency of this simple thing. Thanks!

**Comment by jcr** [comment]
done,
