### ISSUE TITLE
Search options

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#22]
The search options on the whole website could be improved. I saw a ticket open about the LL, but also on the Land debate there could be some useful changes.

If you enter a search term in the search box in the Land Debate, the results show up somewhat randomly. If you would click on an existing tag with that term, you get a much more relevant list of hits (from most recent to older). Is it possible to use that display of hits for the search box on top? (through the tags)

Also, I feel it could be convenient to have a search option not only on the specific services of the website, but on the hub page as well.

**Comment by jcr** [comment]
new search is in place.  We still have to add the Overarching + themes filters.
