### ISSUE TITLE
LLR resource view - language display issue

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#220]
When an item is language neutral (default), the text "Also available in" shows up with no apparent reason. Firstly, this should not appear if there aren't actually any links to other languages for the resource. Secondly, this should not be placed there and shift the whole view - it should be placed neatly in the right column with the rest of the information and how it was documented in the web structure document.

<img width="1280" alt="screen shot 2017-01-24 at 10 47 09" src="https://cloud.githubusercontent.com/assets/6312043/22242317/284f7f5c-e223-11e6-8b82-fb7a83a66f54.png">

**Comment by jcr** [comment]
for now this field is hidden.
Once we fix and sort out (soon) the translation issue we will re-enable it and show it when we have translation for the Library resource (#121)
