### ISSUE TITLE
LLR form improvements

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#221]
The LLR form should be changed in some ways to make it more intuitive and look better in general.

<img width="1280" alt="screen shot 2017-01-24 at 10 53 06" src="https://cloud.githubusercontent.com/assets/6312043/22242372/61737f22-e223-11e6-811e-fe55eb3ce66e.png">

1. The "access to the resource" should not be on the right but directly below the Description field. It is fine if it takes up the whole width. It has happened to me several times now when adding a resource that you easily overlook these fields are they are hidden away to the right. These fields are not mandatory (bc there are either/or options to add resource URL, to upload, or original publishing page), but the most important ones of all the fields.  --> perhaps they can be placed next to each other but on a new line. So: resource url - file upload - originally published at - thumbnail, horizontally next to each other.

2. The resource type is currently overlapping with the the "about the resource" title. That should be moved lower so they don't overlap.

3. The explanatory text with some of the fields are BEHIND the box to enter fields, making it impossible to read. That should be placed under the text box again. And in some cases (for some reason with the corporate author for example) the explanatory text is IN the text box. The text box is not long enough, so again, you're missing a lot of the text. That should also be placed BENEATH the entry box.

4. Publishing rights should by default be UNFOLDED. Now it's folded, and therefore easy to skip. We want to encourage people to enter this information as much as possible.

**Comment by jcr** [comment]
massively improved by today's release.
To be continued...
