### ISSUE TITLE
Improve the alignment & space (padding) in the details of a LLR

### ISSUE THREAD

**Issue by dayures** [landportal/drupal#228]
In the image (taken from https://landportal.info/library/resources/housing-land-and-property-rights-somalia%E2%80%99s-urban-displaced-women), it looks like there should be more space between the label and the value of the field. Also some aligment.

![captura](https://cloud.githubusercontent.com/assets/1654811/22289501/3bf2a514-e2fc-11e6-98c3-0d2d72249b53.PNG)

**Comment by jcr** [comment]
better already?

**Comment by lisettemeij** [comment]
Reopening this issue because there are still no spaces between the label and the input:

![screen shot 2017-09-15 at 15 50 10](https://user-images.githubusercontent.com/6312043/30485453-ba61f588-9a2d-11e7-86fa-a657d3d7400f.png)

Screenshot of same page Carlos linked to in his post.
