### ISSUE TITLE
Improve the download section

### ISSUE THREAD

**Issue by dayures** [landportal/drupal#230]
For instance: https://landportal.info/book/indicator/nkt-vggt16-3g

- [ ] Create an image for Download (as the ones in Mapping, Ranking...)
- [ ] Add an icon for csv, json, xml..
- [ ] Add a link to the SPARQL query 
- [ ] Add background grey to distinguish between blocks
- [ ] Remove the symbol before "Download the data for"

**Comment by jcr** [comment]
done?
