### ISSUE TITLE
Location fields (organizational profile) not usual address fields

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#238]
When you add a location of for example an organizational profile, the fields to enter are not very usual for an address. See below:

<img width="1280" alt="screen shot 2017-01-30 at 10 18 55" src="https://cloud.githubusercontent.com/assets/6312043/22417671/abcef9a0-e6d5-11e6-81f9-5ce199095d95.png">

That there is a location name make sense, especially for addresses in the global South, but the rest (other than country) don't really make a lot of sense.

I would suggest to change to:

- Location name
- Address
- City
- Postal code
- Country.

**Comment by jcr** [comment]
removed coordinates fields, added the others + province / region (if we ask to provide and address we might as well do it completely)
