### ISSUE TITLE
All content types added by LP users by default should be "published"

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#239]
All content types added by LP users by default should be "published".

This is the case for some content types, but for example with organizational profiles, the default setting is "unpublished". 

For LP users anything they add should be default published.

**Comment by jcr** [comment]
There is already a ticket open related to that #170 (I agree the title isn't good)

Nonetheless your statement is false (all content should be published by default) this is not what we decided back 6months ago.

Also provide some links or more proper doc if you have better (already lost 1/2h try to get the picture of the board we took in Roma).

> This is the case for some content types, but for example with organizational profiles, the default setting is "unpublished".

Last, I appreciate your suggestions to tell me how to do my job but this is not how it works.

**Comment by jcr** [comment]
wtf, github lost my comment...
In short, I said this is a duplicate of #170 and I couldn't find the picture we took in Roma (at least the other ticket point to some document).

I think your statement is false, not all CT should be published by default (org profile, debates and even LLR? shouldn't)

Thanks for telling me how to do my job it but this is not how it should / is going to be done (default setting on the CT).
There is a rule (workflow) already set to automatically publish under certain conditions. I have to check why it's disabled.
