### ISSUE TITLE
Overlap with "view" "edit" "manage display" labels with rest of content

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#240]
Hi,

Sometimes there is a harmful overlap with the "view" "edit" and "manage display" labels when you're logged in on the right top side of content. In the editing form, you sometimes can't ready what is underneath and sometimes even can't click the link underneath it.

See here:
<img width="1280" alt="screen shot 2017-01-30 at 13 15 14" src="https://cloud.githubusercontent.com/assets/6312043/22424009/d758feda-e6f4-11e6-9ce1-67ee3434d2cf.png">

Can we fix this that the text automatically gets pushed downwards if you're logged in and this extra menu shows up?

Thanks!

**Comment by jcr** [comment]
should be fixed by last releases - re-open if it's still there
