### ISSUE TITLE
AJAX error on node creation forms

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#245]
I get the following AJAX errors more often now when I'm adding resources to the website. See the screenshots below:

<img width="1280" alt="screen shot 2017-01-31 at 10 26 31" src="https://cloud.githubusercontent.com/assets/6312043/22459194/f0bd4df8-e79f-11e6-8a49-45924a60467d.png">
<img width="1280" alt="screen shot 2017-01-31 at 10 24 55" src="https://cloud.githubusercontent.com/assets/6312043/22459193/f05ab12a-e79f-11e6-8c97-b86e39364f16.png">

These were taken while I was trying to upload a logo, but it has also happened when I tried to click the "publish" button, or something else that the page had to 'load'.

As said, this doesn't happen every time, but I'm encountering it more often.

To go with the log of errors Jules requested, I've seen this mentioned in November last year (that I could find) and I've also mentioned it to Carlos last week that it happened a couple of times. Searched Github and couldn't find anything similar mentioned here.

**Comment by jcr** [comment]
Let try to put down some facts:
- doesn't seem to be link to the OS or browser
- the alerts are on (maybe more)
  - location field
  - image field

The jQuery version in lpbs (theme) is 2.1.4

**Comment by jcr** [comment]
Also happened on CT events, field file

**Comment by jcr** [comment]
Closing this as it doesn't seem to occur anymore
My guess was that is was essentially reminiscences of the old scripts and cache when we published the new theme.

Re-open if you still have this bug of course
