### ISSUE TITLE
Can't add a file to events, get ajax error

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#246]
![image](https://cloud.githubusercontent.com/assets/23736268/22459409/c1e38186-e7a0-11e6-8a30-2f063bc942db.png)

**Comment by jcr** [comment]
let's close this one as a duplicate of #245.
For the record, if you hit this bug again, please comment directly on #245 providing at least the page where that happen and if possible the field or error mentioned.
thanks
