### ISSUE TITLE
Display: "access original publishing page" similar to "download resource"

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#250]
Can we change the display of the "access original publishing page" (screenshot 1) similar to how "download resource" (screenshot 2) looks like?

Screenshot 1:
<img width="1280" alt="screen shot 2017-01-31 at 17 24 45" src="https://cloud.githubusercontent.com/assets/6312043/22473798/4ca4b022-e7da-11e6-821a-1aae0de23f0a.png">

Screenshot 2:
<img width="1280" alt="screen shot 2017-01-31 at 17 26 02" src="https://cloud.githubusercontent.com/assets/6312043/22473831/5feb64a0-e7da-11e6-942e-9be0795a1862.png">

**Comment by jcr** [comment]
fixed and baked in the latest code update

**Comment by dayures** [comment]
fixed in landportal/drupal-lpbs@d08f382b4c106f1db24f26f00c16334cd557e5d2
