### ISSUE TITLE
Pictures not showing up on profiles

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#251]
Although I upload pictures systematically for all users, they are no longer showing up on profiles. They only show up if I add the secondary picture that is not readily accessible by other people. The picture people upload has to be visible. Please reconcile the two image fields to ensure the maximum number of users have images.

![image](https://cloud.githubusercontent.com/assets/23736268/22543853/af541880-e932-11e6-9774-fcf7fb23c818.png)

**Comment by realneilsorensen** [comment]
For instance, I uploaded this picture: 
![image](https://cloud.githubusercontent.com/assets/23736268/22544541/7d43a808-e935-11e6-8e8e-8c5efec51747.png)

But it doesn't appear on her profile: 
![image](https://cloud.githubusercontent.com/assets/23736268/22544558/94aa2fb2-e935-11e6-879d-78942cf01294.png)

I have to go back and edit the profile and upload another copy of the picture in a different place:

![image](https://cloud.githubusercontent.com/assets/23736268/22544594/c654ced2-e935-11e6-8b1f-6022af62a1e0.png)

This creates a duplicate of the picture that is already online:

![image](https://cloud.githubusercontent.com/assets/23736268/22544613/dd78f50c-e935-11e6-916e-b77351dba843.png)

This has got to be fixed, it is affecting many, many profiles.

**Comment by jcr** [comment]
this is all re-done and cleaned. Visible on stage and will be pulled into production this morning.
