### ISSUE TITLE
Image Browse Field in Debates Unclickable/Can't upload image and thus cannot publish debate

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#253]
With the new updates, it has become impossible to upload an image in the debates. The browse image field is unclickable. Images are required obviously and thus the debate cannot be published. We have commitments with our donors/partners to publish this online now, and thus this is urgent. I tried to open new window, but I have the same problem every time. Look at the cursor. Normally there would be a hand if the browse field were clickable. There is not, just the normal cursor.

![image](https://cloud.githubusercontent.com/assets/23736268/22584584/826c9fba-e9f3-11e6-9e60-cc4ec9e7f80b.png)

**Comment by jcr** [comment]
fixed by the update on contributors form (all the forms have been reviewed - also with a contributor level account)
