### ISSUE TITLE
Country + Thematic page - Re-add link to "all LL resources"

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#254]
Please re-add the link to "see all" LL resources on the bottom of the country and thematic pages. The link should go to the search feature with LL > country/theme filter.

That was somehow deleted with the new launch.

**Comment by jcr** [comment]
FYI there was never a thematic library page.
and no we don't want to go to the search feature of the LL this would be the worth thing to do (I already tried to explain many time why. A SEARCH ISN'T A GOOD WAY TO BROWSE!)

**Comment by lisettemeij** [comment]
of course there is no thematic library page, I meant the library block on the thematic page.

https://landportal.info/book/countries/BOL
<img width="1280" alt="screen shot 2017-02-15 at 09 58 02" src="https://cloud.githubusercontent.com/assets/6312043/22967072/3e2a7112-f365-11e6-9042-d99ae6ca6836.png">

Here should be a link to all library resources, because now you just see "Displaying 6 of 41" and there is now way to see more. This link used to be there before when Simbiosys launched the pages.

Another thing: the order here should also be most recent LL resource on top (similar to LL display result on an organizational profile), not latest added to the LL as it is now.

**Comment by jcr** [comment]
done.
Now we also have functional browse views by geographical focus and themes on the library
