### ISSUE TITLE
Publisher should be deleted from the LL teaser view

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#255]
The publisher should be deleted from the Land Library teaser view.

See below: it unnecessarily clutters the view:

<img width="920" alt="screen shot 2017-02-03 at 10 11 39" src="https://cloud.githubusercontent.com/assets/6312043/22585660/32f3ce4e-e9f9-11e6-974c-131c72455ce3.png">

Please only have thumbnail, date, title, description and geographical focus like I mentioned before until Simbiosys can look at a more intuitive design to show this.

**Comment by lisettemeij** [comment]
Data provider should too, it is looking really cluttered and randomly placed. Please keep it as simple as possible until Simbiosys has taken a look at it:

<img width="1097" alt="screen shot 2017-02-03 at 10 19 32" src="https://cloud.githubusercontent.com/assets/6312043/22585866/45f518a8-e9fa-11e6-976e-747229f8c864.png">

**Comment by jcr** [comment]
done in #facdc51
online already
