### ISSUE TITLE
Land Book country/thematic pages: partner filter

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#256]
What is the filter for the partners showing up in the partner block?

There are organizations showing up that are only tagged with "Land Library content provider" and those should NOT show up there.

Now for example, we have Cambodian ministries showing up on the urban tenure thematic page: https://landportal.info/book/thematic/urbanization

We haven't clearly defined who LP partners are yet but this filter is definitely not it!!

**Comment by jcr** [comment]
Hi Lisette,

AFAIK every organization (or content) tagged with the "thematic" is showing up.
While the title is "Partners" - which is the confusing bit - I believe it's a good thing to show who is working on such issues.

When we're at a point of narrowing it down because we have too many results.

**Comment by lisettemeij** [comment]
Yes, sure, but the title above the block is "Partners" and that is misleading.

So for now, please only have the organizations that are tagged with the theme + "Land Portal partner", so we don't show ministries of developing countries that we've never actually talked to as our partners.

**Comment by jcr** [comment]
OK - your call

**Comment by jcr** [comment]
We are now showing organizations that 'relates' to this theme (theme + concecpts) tagged as partners (we can make this changes along the lines of what we discuss during last team call).
