### ISSUE TITLE
File upload field not visible publicly (LLR)

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#257]
The links to download a file from publications in the Land Library do not show up in Internet Explorer, perhaps also not on Safari:
![image](https://cloud.githubusercontent.com/assets/23736268/22647869/06ab747c-ec74-11e6-89c5-de027ec9e3e6.png)

This is how it looks in Chrome (with download link):

![image](https://cloud.githubusercontent.com/assets/23736268/22647920/3b5cdcec-ec74-11e6-8bc3-2f62e62ff9f5.png)

This is a serious problem that must be dealt with immediately.

**Comment by realneilsorensen** [comment]
The problem is worse than I thought. The download link is not visible in Chrome either when logged out of the Land Portal.

This is how it looks in Chrome when not logged in:

![image](https://cloud.githubusercontent.com/assets/23736268/22650041/ba28f296-ec7d-11e6-8108-72736ebb710e.png)

Note, the download link is no longer visible.

**Comment by dayures** [comment]
The issue looks like only affects "File uploaded" field. 

For instance, http://landportal.info/library/resources/reflections-future-challenges-housing-land-and-property-restitution-syrian has a "download resource" (from Resource URL field)

**Comment by dayures** [comment]
As a hotfix, in the LLR from the example, the field "Resource URL" has been filled with a value

http://landportal.info/library/resources/2016-dfid-land-portfolio-overview

**Comment by jcr** [comment]
fixed and backed in code.
