### ISSUE TITLE
Library resource teaser view - overlapping text

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#261]
There is overlapping text of the resource type and the publication date in a teaser view of a LLR.

See the page here:
http://landportal.info/library/search/land#

And the screenshot here:
<img width="1280" alt="screen shot 2017-02-21 at 12 22 17" src="https://cloud.githubusercontent.com/assets/6312043/23162876/67ee3d92-f830-11e6-880e-b6159721cbd8.png">

Can we put the date BELOW the resource type?

Thanks!

**Comment by jcr** [comment]
fixed in last layout/style update
