### ISSUE TITLE
"Thematic promoted" shows up below abstract of LLR page.

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#264]
When a LLR is promoted to a thematic portfolio, it shows up on the LLR page below the abstract. See link and screenshot below:

https://landportal.info/library/resources/risk-and-conflict-peace-and-prosperity
<img width="1280" alt="screen shot 2017-03-03 at 08 55 42" src="https://cloud.githubusercontent.com/assets/6312043/23542799/6e6a0aea-ffef-11e6-994f-b034249c1d5e.png">

Can we make sure that doesn't show up?

I checked with another resource and it doesn't happen if something gets promoted to a country portfolio.

Oh and just a note that it says on a lot of places "thematic" (for example also in the URL), but that is the adjective and therefore should only be used when the word 'portfolio' or 'page' is following it. In all other instances, it should just be THEME. 

Thanks :)

**Comment by jcr** [comment]
Was cleared at the last update
