### ISSUE TITLE
Can we force embedded videos to fit the width of the column it's embedded in?

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#265]
Hi,

Can we force the width of embedded videos to not exceed the width of the column it's embedded in?

See for example the screenshot below:

<img width="1280" alt="screen shot 2017-03-03 at 09 07 43" src="https://cloud.githubusercontent.com/assets/6312043/23543125/038d857e-fff1-11e6-8489-5f95a235c6cf.png">

This is the link: https://landportal.info/library/resources/dynamics-land-deals-africa

I've altered the embed code now to fit my own laptop screen, but that still might be too broad for other screens. Also, it requires adjusting an HTML code, which a lot of people won't do probably.

Can we make sure that this happens automatically?

**Comment by jcr** [comment]
done.
now, by default, iframes (for embeded media) show in full width of the body.
