### ISSUE TITLE
User images no longer related to organizational profiles

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#266]
User images of those who work for organizations represented on the Land Portal no longer appear on the Land Portal. This is likely also related to another bug I posted on GitHub noting that the images are mixed up, there are two fields and now the standard image field was switched for the other field, apparently, eliminating many images from profiles. This should be fixed asap.

![image](https://cloud.githubusercontent.com/assets/23736268/23709656/70e992de-041a-11e7-9219-f25216bb4791.png)

**Comment by jcr** [comment]
Fix on stage and will be pulled into production this morning.
