### ISSUE TITLE
New 'image' item in LL resource besides 'thumbnail' - and only image shows up. 

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#271]

**Comment by lisettemeij** [comment]
Sorry, pressed enter too soon :) 

For some reason, there is an image field in the LL resource form now.

The thumbnail field still exists, but when I uploaded a thumbnail to a new resource just now, the thumbnail didn't show up. The image next to the abstract just had the default 'no preview available' picture.

It is not very intuitive to not use the 'thumbnail' field for the actual thumbnail and to have a second field for that.

So firstly: can we make the thumbnail field again the field where you should actually upload the thumbnail?

And secondly, any explanation how this happened or why this got changed? Just for the future, I would like to be kept in the loop if there are any changes to anything concerning the LL, as I'm the product owner :)

Thanks!

**Comment by lisettemeij** [comment]
Just to give you more info, this is the resource I was adding:

https://landportal.info/library/resources/collaborative-approach-human-rights-impact-assessments

If you go to the form, you'll see that the thumbnail is added to both the 'image' and the 'thumbnail' field. if you remove the image, the thumbnail will not show up on the LLR page.

For the other resource, even though they got added before the new 'image' field was introduced last week, the thumbnails still show up properly thankfully.

But if we can change this back as soon as possible, that would be great.

**Comment by dayures** [comment]
related c988e91a216080aa628013a5d87da85a5c2836f6
