### ISSUE TITLE
Strange alignments in some part of the website

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#273]
Hey,

There are some alignments (center, left) that don't always look very good. Found two examples today:

Home page:
![screen shot 2017-03-31 at 09 54 42](https://cloud.githubusercontent.com/assets/6312043/24541553/45575ba2-15f8-11e7-86dc-520e6775c53d.png)
(See how landbook, etc. are aligned to the left and then the text below is centered?)

LLR page:
https://landportal.info/library/resources/briefing-note-collaborative-approach-human-rights-impact-assessments
![screen shot 2017-03-31 at 09 55 04](https://cloud.githubusercontent.com/assets/6312043/24541569/54ed1c64-15f8-11e7-9808-c5e90c72c4a5.png)
The acronym of the organization seems to be centered while the logo is on the left. Therefore they don't really look like they're supposed to be together. The CCSI one in particular in this screenshot).

**Comment by jcr** [comment]
yes, this is pending a style fix I want to release today (early pm).
For the home page we will move the 3 blocks in the page content so they can be edited (and more stuff added above and below).

**Comment by jcr** [comment]
all cleared.
The last update included a bit of re-work on grids and layout to make them more consistent across the site.
