### ISSUE TITLE
Create a 'promote to LL landing page' option for LLRs

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#275]
Hi,

With the promote to front page option now actually applying to the front page, can we instate a new option to promote to the LL landing page? We want to be able to feature the latest publications there, that don't necessarily warrant a place on the home page.

That option is currently not there:
![screen shot 2017-03-31 at 09 53 49](https://cloud.githubusercontent.com/assets/6312043/24541736/fa2d85ba-15f8-11e7-8684-9430e58c2bb4.png)

Thanks!

**Comment by lisettemeij** [comment]
Any news on this? Just asking because Jules said in the chat that this was something that can be really quickly implemented.

**Comment by jcr** [comment]
done and published
