### ISSUE TITLE
About us menu - menu bar disappears on Contact form page

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#276]
Hi,

If you go to the 'Contact us' menu item in the drop down menu on the about us page, you are directed to a page where the brown menu bar disappears:

https://landportal.info/about
![screen shot 2017-03-31 at 10 12 31](https://cloud.githubusercontent.com/assets/6312043/24542080/94d3b03e-15fa-11e7-886a-6c650b41023f.png)

https://landportal.info/webform/2016/04/contact-form
![screen shot 2017-03-31 at 10 12 35](https://cloud.githubusercontent.com/assets/6312043/24542086/98360934-15fa-11e7-8016-07a450b91d31.png)

Is it possible to include the brown menu bar to the contact form page? 

(and perhaps change the url to something more permanent, not including the date - I thought that was done at some point already?)

**Comment by jcr** [comment]
the link was incorrect, and  shouldn't have brought to this page.
fixed.
