### ISSUE TITLE
Uploaded LL Thumbnails not showing up anymore

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#277]
Hi guys,

Since you changed the 'thumbnail' image to 'image', now the thumbnails that were uploaded to 'thumbnail' field are not showing up anymore. E.g.:

https://landportal.info/library/resources/land-rights-matter-anchors-reduce-land-grabbing-dispossession-and-displacement

https://landportal.info/library/resources/convergence-under-pressure

These are resources I manually added, so I know 100% sure that they had thumbnails.

Please change back whatever you did. I wanted to make screenshots of the website for a presentation, and I just can't do it with these broken links.

**Comment by jcr** [comment]
Both images are back.
FYI this had absolutely nothing to with this field being renamed but I indeed discovered hundreds of images and files missing.
All the images used to illustrate content should be back, at least in the DB. I am not yet sure we have 100% of the physical files and all the images generated thumbnails are correct but I will investigate more on that today and try to understand how come those were missing in the first place.

If I may, I'd suggest the appropriate report could have simply be " images don't work for those resources ". Please don't assume it's something specific when not 100% sure - it's like adding another " bug " on top of it as I also have to debunk what is true or not before getting to the real one.
Thanks again for the nice mail to team that was lovely
