### ISSUE TITLE
Add new field in LL  form - linking conference paper to event node on LP

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#279]
Hi,

I realize this isn't a Drupal issue, so shouldn't be posted here, but I can't find the general development plan for the Land Library. 

I would like to add a new field in a LL form. I can arrange that in the form in a place that it does not confuse people that don't need to do anything with it (I'm thinking a default collapsed section).

We need to be able to link a LLR to an event node on the Land Debate. Ideally this field would only show up when the resource type 'conference papers & reports' is selected, but I can imagine that complicates things a bit. So for now placing it in a collapsable box and I will add description text to it will be fine for now.

If this can be implemented quickly (I imagine this is fairly easy) that would be great, because I am going to add the papers of the India conference we have here. At least then when I'm adding the resources, I have the metadata (incl. linking to an event) complete and I don't have to go back at a later time.

This should be shown on the LLR page on the right column with a separate header 'Related content'. The input would be 
Events: [text with name of conference]

I think text is better because we don't need a big picture, something that steals the attention of the actual LLR.

Then on the Land Debate event page, I would show it on the right column ideally (instead or above the twitter feed). If that is too complicated because the teasers take up too much width, for now I guess we could place it below the description of an event in the middle column.

Then we could address it with the redesign and make sure that it can be featured nicely.

Again - if this could be implemented quickly that would be really great! Can you give me an estimation when this can be finished? (at least the field for the metadata part?)

**Comment by jcr** [comment]
done, now this also link both ways
https://dev.landportal.info/node/70976/edit
https://dev.landportal.info/node/63098/edit
