### ISSUE TITLE
Fields in LLR form jump around when filled in

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#280]
Hi,

Sometimes when you fill in a particular field in the LLR form, the fields start to jump around on the screen and are re-arranged.

See the two screenshots below:

![screen shot 2017-04-10 at 10 20 23](https://cloud.githubusercontent.com/assets/6312043/24852324/551a2f4c-1dd7-11e7-9a0f-a738c75da0cc.png)
![screen shot 2017-04-10 at 10 19 35](https://cloud.githubusercontent.com/assets/6312043/24852325/55363a70-1dd7-11e7-8593-8c736fb6e9e9.png)

When you fill in the LLR type field, there suddenly needs to be a big space below and all the fields are pushed and re-arranged differently.

This is not particularly urgent or something, but just a bit weird and not so professional-looking so wanted to flag it. So when someone has a chance, could you take a look at it and make sure the fields don't jump and re-arrange for no particular reason?

Thanks!

**Comment by lisettemeij** [comment]
It's just a bit confusing because some of the fields seem to switch from the right side to the left side and the other way around. So then it takes you a few seconds to find the fields again.

Again- no big deal and nothing urgent, but just to flag that this somehow happens.

**Comment by lisettemeij** [comment]
When I fill in resource language, I guess it jumps back:

![screen shot 2017-04-10 at 10 22 54](https://cloud.githubusercontent.com/assets/6312043/24852424/b38c9768-1dd7-11e7-9098-1ab7a085c4f3.png)


Very weird!

**Comment by jcr** [comment]
hey Lisette,
Indeed it was a weird unintended effect of having 2 columns. I will spare you the pretty fun tricky details of why it was doing it.
Should be all fixed!
