### ISSUE TITLE
Portuguese footer translations / links issues

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#282]
Hi,

This was addressed by Pedro, our Portuguese news contributor:

**Links ( please go to any Land Portal page and scroll down):
-Preguntas Frecuentes ( That's spanish and in Portuguese we say "Perguntas Frequentes");
-"Termos e Condições" and "LandVoc" pages link directly to the homepage and not to the portuguese section of "terms and conditions" and "LandVoc";
- Contato conosco is wrong. Should be "Contacte connosco". Also, in that same page we can see "name " and "your message" instead of "nome" and " A sua mensagem".**

Can someone please fix these issues? I prefer not to touch the footer translations and stuff, because it seems quite delicate and everytime I change something, something goes wrong or something disappears or something.

Would prefer the Drupal experts to take this one ;)

**Comment by jcr** [comment]
yes menu and translations were a bit messed up under the footer landportal part.
I have fixed the links in all 3 languages
