### ISSUE TITLE
Connection with Mailchimp does not seem to function

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#283]
The connection to Mailchimp does not seem to be functioning and has not worked for a long time. This can be seen through the lack of evolution of the Mailchimp subscriber growth, which is non-existent. Also, I have seen many message saying there is a problem with the connection to Drupal (and have reported on this previously).

Thanks for looking into this. It's really important the link to Mailchimp functions correctly.

**Comment by jcr** [comment]
after check, the connection seems to be working
