### ISSUE TITLE
LLR page layout

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#284]
Hi,

The placement of the Resource title of a LLR has changed to the middle column above the abstract field. See screenshot below and link:

![screen shot 2017-04-11 at 10 47 48](https://cloud.githubusercontent.com/assets/6312043/24900533/7603f36e-1ea4-11e7-9b8b-6dfd966d8771.png)

Link: http://landportal.info/library/resources/urban-land-markets-east-africa

Can we change that back to on the left side (taking full width of the screen) below the resource type (which is in a lighter font) and above the thumbnail image? You can see an example in the web structure document (basically the same as it was before).

The subtitle (not there in this example) should be below the title, in a slightly smaller font and similar to LLR type, in a 'light' format.

Thanks!

**Comment by lisettemeij** [comment]
Oh, and the subtitle should have the same color, just plain black :)

**Comment by dayures** [comment]
Today is working properly on production
