### ISSUE TITLE
Unable to translate - Land Book country pages elements

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#285]
Hi,

Working on the Portuguese translations now, documenting those that I can't do myself here:

I am unable to insert the translations for the menu on the country pages:

http://landportal.info/pt/book/countries/BOL

-> Country narrative, Indicators, Compare Countries... etc.  That menu.

**Comment by lisettemeij** [comment]
Same counts for the Download PDF and Give us your feedback links on the same page

**Comment by lisettemeij** [comment]
And for the disclaimer on that same page. (even when I tried to make the block translatable in Beta)

**Comment by lisettemeij** [comment]
And the note under the LGAF indicator ("Note: Some Indicators might have multiple values (e.g. Green-Orange), which might refers to different localities or categories of people. For more information please refers to specific country reports and to the methodology made available by the original data source/provider: The Land GovernanceAssessment Framework (LGAF) website of the World Bank")

**Comment by lisettemeij** [comment]
And the notes under the VGGTs indicator

**Comment by lisettemeij** [comment]
And under the Spider Chart (under 'Main Indexes')

**Comment by lisettemeij** [comment]
As well as all static texts and header images.

**Comment by jcr** [comment]
ok let's summarize there;
First a few other fixes on CP have improve some aspect of that. the internal page navigation items now are directly the same as the sections /blocks title (ie. if translated correctly the page internal menu will be translated).

For blocks like compare, indicators, library and partners blocks (tested on stage), the way to translate those sections title is:
 - go to configure the block.
 - set an English title if there is none (on https://stage.landportal.info/admin/structure/block/manage/landbook_vis_table_indicators/country_values/configure), check the option " Make this block translatable" under language - save
 - then you will have a translate menu

Blocks that needs fixing (hardcoded...)
- [ ] disclaimer and pdf+feeback blocks content should be editable + translatable
- [ ] spider chart, VGGT, LGAT blocks notes/disclaimer

note sure what you meant with the last comment "As well as all static texts and header images." ?

**Comment by jcr** [comment]
to be checked but AFAIK this should work fine for the remaining blocks that'll be on dev.
Of course translation of dev will be a whole new story we should start checking the menus soon and various block titles as well, create tickets and tracking notes for this on the wireframe site +docs.
