### ISSUE TITLE
Organizational profile CT - acronym is placed too far away from organization name

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#286]
When adding an organizational profile, the acronym is suddenly placed way more to the bottom than it used to be before. It is much more intuitive if the acronym is close to where you input the name of the organization. Before it was aligned to the right, similar to the logo. 

Link: http://landportal.info/node/add/organization
Photo:
![screen shot 2017-04-28 at 13 36 58](https://cloud.githubusercontent.com/assets/6312043/25527210/fa523fa6-2c17-11e7-9f4e-1b44a1251d9b.png)

**Comment by lisettemeij** [comment]
Also, I'd recommend to leave the 'location' field default un-folded. Now it is folded by default, which makes it really easy to overlook. 

This is information that we would potentially / probably be using in the future to determine how much organizations are based particular countries in the global South. So it is important that people fill it in.

**Comment by dayures** [comment]
already fixed (some commits around 13 jul 2017)
