### ISSUE TITLE
Search box - advanced search collapsed (even after features are used)

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#287]
Hi,

When I use the general search box on the website, I often use the advanced search for a particular content type. This advanced search box is collapsed by default, which is fine. But after you've hit 'enter' and it loads the results page, the advanced search box is back to being collapsed again.

My example: http://landportal.info/search/all/%2522Administraci%25C3%25B3n%2520de%2520la%2520Comunidad%2520Aut%25C3%25B3noma%2520de%2520Euskadi%2522?f[0]=bundle%3Aorganization

![screen shot 2017-04-28 at 13 45 49](https://cloud.githubusercontent.com/assets/6312043/25527481/36a52346-2c19-11e7-9e09-f5a487b4c185.png)
![screen shot 2017-04-28 at 13 45 01](https://cloud.githubusercontent.com/assets/6312043/25527482/36c28b98-2c19-11e7-9466-df8fdb272d6c.png)

Is there any way that the page can remember if you uncollapsed that before and keep it that way when it shows search results? I often find myself uncollapsing it again to make sure the filter was actually applied.

**Comment by jcr** [comment]
new search deployed.
I am closing this as it was more related to a usability issue which is now solved.
We will re-open search, advanced search, improving filters (on the side) in time. (maybe we can already open a ticket to have the select/dropdown option+search for countries and landvoc concepts).
