### ISSUE TITLE
LL - promote to country page feature not working

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#288]
Hi,

I've posted this a while back but can't find it, so adding it again.

The promote to country page feature is still not working on a LL resource. You can tick the box but it doesn't show you a box where you can enter which country it should be promoted to.

Can we fix this ASAP? Thanks!

**Comment by jcr** [comment]
I know you gonna hate me but as pointed on a hangouts chat, this works as intended.
We could make use of the sticky parameter to make sure a promoted item is shown first (to be implemented).
