### ISSUE TITLE
LB - Repeated dataset names in the scroll down menu

### ISSUE THREAD

**Issue by MarcelloLP** [landportal/drupal#289]
In here [https://landportal.info/book/indicators] the drop down menu for datasets repeat twice the name of the dataset, showing after the actual dataset name the following sentence: "Rendered Taxonomy Terms: [DATASET NAME]".

See screenshot.

![screen shot 2017-05-02 at 11 37 24](https://cloud.githubusercontent.com/assets/22029957/25615013/bd075cb8-2f2c-11e7-8b5a-27b8d887dcc1.png)

**Comment by jcr** [comment]
- to be confirmed - more details needed
