### ISSUE TITLE
LL - some help texts in LLR fields not showing up

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#290]
Hi,

In the LLR form, with some of the fields there are help texts with links entered. Not all of them actually show up on the pages.

Under LandVoc fields (subject of resource) they do for example, but then 'Resource URL' for example it does not show up on the actual form.

Can we make sure all the help texts show up? (Sooner rather than later, because I want to record this tutorial ASAP).

Thanks!

**Comment by lisettemeij** [comment]
Screenshots of the example I just gave where help text is entered, but doesn't show up on the LLR form:

![screen shot 2017-05-08 at 13 21 21](https://cloud.githubusercontent.com/assets/6312043/25802144/4bc16ad4-33f1-11e7-98c4-65ef4b62d45f.png)
![screen shot 2017-05-08 at 13 21 10](https://cloud.githubusercontent.com/assets/6312043/25802143/4bb9ffb0-33f1-11e7-8ab8-96fea06ffaf6.png)

**Comment by dayures** [comment]
already fixed
