### ISSUE TITLE
LL - Date of publication field adjustment required

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#291]
Hi,

In the LL the date of publication format is MM/YYYY.

However, when you manually add a LLR, you are requested to fill in information in a pop up calendar, including the date of publication.

![screen shot 2017-05-08 at 15 15 51](https://cloud.githubusercontent.com/assets/6312043/25805866/8e466412-3401-11e7-863b-7c01fd64894f.png)

Can we delete this and simply have the MM and YYYY forms, like we had before? 

This way you don't have to fill in information that is not going to be saved + helps a lot because often the actual date is not published, often only months or sometimes even only year. But date is definitely missing most of the time.

For this also counts, the sooner, the better 'cause I'd like to include it without this pop up calendar in the tutorial.

Thanks!

**Comment by jcr** [comment]
check also date(s) fields on other CT, exemple
http://dev.landportal.info/node/add/event

see date fields at:
http://dev.landportal.info/admin/reports/fields

**Comment by jcr** [comment]
fixed, see beta https://beta.landportal.info/node/add/landlibrary-resource
