### ISSUE TITLE
Land Library admin view

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#294]
Hi,

One quick question - is it possible to include in the LL admin view, the location country of the publisher? Perhaps also the organization type? So that is an entry field in the organization CT - which is really useful to know the # of local sources in the LL.

I counted this manually for the Library presentation at the annual meeting last year - but as we're exceeding 500 publishers soon, I don't think I will be able to do it.

I'm not sure if the LL admin view is the best place to do this..... any suggestions as to how best get these results would be really appreciated :)

**Comment by dayures** [comment]
solved using SPARQL :)

https://github.com/landportal/data/blob/master/landlibrary/stats/Land%20Library%20Stats.sparql
