### ISSUE TITLE
Profile pictures for users not appearing on blogs, etc.

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#295]
I've mentioned this before, but the profile pictures for users no longer appear on their profiles and now appear through a second image field that was not used before. 

![image](https://cloud.githubusercontent.com/assets/23736268/26047292/d437e33c-3952-11e7-8a62-cc20924cde92.png)

Anne Larson, for example, has an photo, which I included in her profile for a previous blog, but now it does not show up any more. 

This is a serious bug and must be fix. The image fields must be reconciled, as now we have a fairly large group of users with a different primary image field that the majority of users. The longer this goes on the bigger the problem will get.

**Comment by realneilsorensen** [comment]
![image](https://cloud.githubusercontent.com/assets/23736268/26047464/930bc6d4-3953-11e7-9783-aaa7ae529119.png)

This is the picture that I previously uploaded and no longer appears on her profile. I had to upload another picture to this field under account:

![image](https://cloud.githubusercontent.com/assets/23736268/26047501/b98a2346-3953-11e7-87b0-7cda48dc16ce.png)

**Comment by jcr** [comment]
this is strange,
here is what I get on her profile page:
![screenshot-landportal info-2017-05-15-10-37-28](https://cloud.githubusercontent.com/assets/446609/26049146/4996740c-395a-11e7-8d7c-c659ca6f4611.png)

Anyways, for this ticket and many other opened ones related to users and pictures I should have an update ready to publish by tomorrow to improve (a lot) the followings:
- user profile page (this one)
- the public profile snippet
- the account forms

**Comment by realneilsorensen** [comment]
That’s because I just uploaded the new picture now because I needed to, as I published a new blog from her.

**Comment by jcr** [comment]
this is all re-done and cleaned. Visible on stage and will be pulled into production this morning.
