### ISSUE TITLE
problem that people's images no longer associated with organizations

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#296]
It's problematic that the users' images and their full names are no longer visible on organizational profiles. It used to look pretty good, now it just looks bad, with the username, not even the real names of the people, no logos, and also lists them as 'Members' which is ridiculous because they work for the organizations where they appear. This has been like this for quite some time, but it bothers me that it was changed in the first place for no apparent reason. I can not recall any discussion that we would eliminate user profiles from the pages of organizations people work for. Please try to fix this.

![image](https://cloud.githubusercontent.com/assets/23736268/26162191/5ba0aba4-3b26-11e7-9ea2-9d9f059b8115.png)

**Comment by jcr** [comment]
dup for #266 
Fix on stage and will be pulled into production this morning.
