### ISSUE TITLE
Bullet points / bootstrapping not working at least in Debates

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#298]
The bullet points in design format show up in the editor but not online when save, so there is a problem with the design implementation.

![image](https://cloud.githubusercontent.com/assets/23736268/26820486/4650e6ce-4aa3-11e7-81af-4a2c42a9f98e.png)

![image](https://cloud.githubusercontent.com/assets/23736268/26820507/5cf44c36-4aa3-11e7-86c0-30717c9a6e61.png)

https://landportal.info/comment/1732#comment-1732

Found here: https://landportal.info/comment/1732#comment-1732

**Comment by dayures** [comment]
Note: The comment is copy&paste, probably from Word, so the HTML markup is messy.

**Comment by jcr** [comment]
commited on the latest theme, will be in production with the next update
