### ISSUE TITLE
Notification for users after they've saved a LLR (or other CT)

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#300]
Hi,

Can we insert some sort of notification for 'regular' users after they've submitted a LLR that their resource is pending approval / publishing from a LP administrator?

Right not it is not so evident that it is not actually online yet after you've hit save (see for example the resource in the LL tutorial). And I've noticed people add the resource several times then because they think something went wrong.

Thanks!

**Comment by jcr** [comment]
just commited (on dev).
Now, LP users will also get an email when they submit some content that isn't published.
There is also a notice on the page (right after clicking save) with a message telling them that it is pending review before being published.
Messages are visible (editable) as admin (need masquerade) at https://dev.landportal.info/admin/config/workflow/rules/reaction/manage/workflow_unpublished 
(and can be further tweaked if needed - but not on dev).
