### ISSUE TITLE
User profile should be part of Debate (navigation above is 'About us' section)

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#301]
Hi,

The user profiles are part of the Land Debate, so should have the Land Debate navigation bar above.

See for example this profile:
https://landportal.info/users/godfrey-massay
<img width="1280" alt="screen shot 2017-06-15 at 09 33 48" src="https://user-images.githubusercontent.com/6312043/27170357-e5e3bf7a-51ad-11e7-9e24-75acfce73308.png">

Can we make sure the Debate navigation shows up there so we are consistent with our pages?

**Comment by jcr** [comment]
not anymore ;)
