### ISSUE TITLE
don't show the list of concepts related to a theme in the view...

### ISSUE THREAD

**Issue by dayures** [landportal/drupal#303]
that it is used in the Landoc main page
http://landportal.info/voc/landvoc

and in the list of themes page
http://landportal.info/voc/landvoc/theme

![captura](https://user-images.githubusercontent.com/1654811/27428212-aea46d86-5741-11e7-85be-edb53fffe005.PNG)

**Comment by jcr** [comment]
Until we have better design / consistency, for now, those should benefit the same rule as we have for node teasers (so should be general to all teasers) which is to hide LandVoc concepts terms.

This view should also probably center teaser content.

**Comment by jcr** [comment]
(hide in CSS - we want those in the markup for SEO reasons)
