### ISSUE TITLE
Please Require Geographical focus and land voc terms for users ASAP!!!

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#307]
![image](https://user-images.githubusercontent.com/23736268/27788739-11265180-5fea-11e7-8311-e6fbf26652d2.png)

**Comment by jcr** [comment]
The Country / location of the user field is now mandatory again (in the live site)

Land voc terms aren't a required field to create a LP account (we could change that later though it would require a bit more work on profiles and UI).
