### ISSUE TITLE
Unclear text included in several teasers: can we remove this?

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#308]
Hi,

There appears to be some italic text that appears below the image in a teaser. It seems to be related to the resource, but seems randomly placed + does not complete where the abstract text on the right was cut off. Can we delete this text from the teaser? See below for an example:

![screen shot 2017-07-12 at 10 10 08](https://user-images.githubusercontent.com/6312043/28108068-845390e4-66ea-11e7-8b1c-dc2a84da3b62.png)

 http://landportal.info/search/all/%2522Recognition%2520of%2520Customary%2520Tenure%2520in%2520the%2520Mekong%2520Region%2522

**Comment by jcr** [comment]
the 'unclear text' is from the search engine, showing what portions of text match on this results.
Without a more proper use (explanation, better results design -or maybe no design-), it is indeed unclear.
Vladimir already removed it in https://github.com/landportal/drupal-lpbs/commit/90f028f382d65f6403070a02a51651e443a2538f

It won't be visible anymore next time we do a release.
