### ISSUE TITLE
Input description text for event dates -> format

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#309]
Please input a description text for the starting and end dates for events.

DD/MM/YYYY. Did it wrong a couple of times but there is no way to see it unless you hit save and it rejects the input:

![screen shot 2017-07-12 at 11 06 23](https://user-images.githubusercontent.com/6312043/28110313-446af29e-66f2-11e7-916b-52713218fc59.png)

Thanks!

**Comment by lisettemeij** [comment]
I just got it to work and apparently the right format is MM/DD/YYYY

This is inconsistent with the rest of the website and also common metadata standards.

Shouldn't we change this and make it consistent throughout the website?

**Comment by jcr** [comment]
yes, this is something we've actually been looking at ( Vladimir )

**Comment by dayures** [comment]
@jcr maybe just use the "widget-type" pop-up calendar in the date field of an event?

**Comment by lisettemeij** [comment]
Thanks!!
