### ISSUE TITLE
Library - upload file box disappears if you tried an image that was too large once

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#310]
Hi,

I tried to upload a file that turned out to be larger than 8 MB to the Land Library. After compressing the PDF and wanting to upload it again, I noticed that the upload file box disappeared! Since I had put in a lot of metadata already, I had to save the file to the server first and then go back and edit the file to be able to upload, which seems a bit excessive.

![screen shot 2017-07-14 at 11 20 49](https://user-images.githubusercontent.com/6312043/28206630-f20dee5c-6886-11e7-8a31-f33d97799175.png)

Any way we can make sure this box does not disappear?

Thanks!

**Comment by jcr** [comment]
Maybe it was due to wrong settings before.
Now I get the proper modal (in-page popup) for the media library + upload. If I upload a file too big I get:
![uploadfail](https://user-images.githubusercontent.com/446609/33645185-cdf6f2b8-da49-11e7-96aa-9f4db2a1b40f.png)
