### ISSUE TITLE
Show title for the Location information

### ISSUE THREAD

**Issue by dayures** [landportal/drupal#313]
Currently, there is no "title" for the information storage in the location field. So when it is displayed, the result is confusing (see screenshot).

The proposal are:
- add more margin on top 
- add a title (fixed "Location", or configurable by Drupal setting)

The template file is: /usr/share/drupal7/sites/all/modules/location/locations.tpl.php

![captura](https://user-images.githubusercontent.com/1654811/28454410-7813c91c-6dfb-11e7-87a9-3b05f8afd807.PNG)

**Comment by lisettemeij** [comment]
Just to add to this, now it seems to somehow show up under the 'Phone number' field:

![screen shot 2017-08-09 at 11 26 52](https://user-images.githubusercontent.com/6312043/29114858-d79fae06-7cf5-11e7-8c14-9504b261444c.png)

https://landportal.info/organization/agricultural-applied-economics-association

Can we simply add a header saying 'Location'?

Thanks!

**Comment by jcr** [comment]
this page still does not look awesome, but the location field label is there apparently (on beta)
