### ISSUE TITLE
Image upload Portal - users from South have issues - possible to link to external image?

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#314]
Hi,

I just got a comment from a user from West Africa who is adding LL resources. Apparently it takes them a lot of time to download + upload an image to use as cover image on the Land Library. They experience regular bad internet connections - something I think we should anticipate for other users from the global South as well.

The thing was that in this case, he has the images on their webpage and he wondered whether it was possible to insert the link, rather than having to upload it to our server.

I told him this is not possible now, but is this something we could consider in the future?

Looking forward to hearing your thoughts!

**Comment by jcr** [comment]
like so (on beta)
![webupload](https://user-images.githubusercontent.com/446609/33644875-e63e5264-da47-11e7-90ee-789639150f2f.png)
