### ISSUE TITLE
Flush cache faster automatically

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#317]
Hi,

As we all know, it takes a while for for example a new organizational profile to show up in a list of publishers (or wherever you need to enter it), because the cache needs to be cleared. 

When adding a land library resource for example with a new publisher, this time that you have to wait is a bit frustrating. While the team knows how to flush the cache to make sure it shows up quickly, users don't know that.

As more local partners are manually adding new profiles and LLRs, I've been getting these comments more and more. It is a general frustration and it really slows down your job. Our local partners are getting paid, but for general users it might be a reason to stop adding something because it takes too long.

So comes my question: is there any way we can speed up this process so that the new inputs show up quicker in a list?

Thanks!

**Comment by dayures** [comment]
@jcr Maybe this module could be useful https://www.drupal.org/project/cacheflush

**Comment by jcr** [comment]
Should not be an issue for org anymore.
The only places where it could take a bit more time to appear (5-10m?) is some few filters list for some front end pages but not on forms.
