### ISSUE TITLE
Leave more vertical space between lines of organizational teasers

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#320]
Hi,

Can we leave some more margin space between organizational profile teasers vertically?

Now they are very close together, see the screenshot below:

![screen shot 2017-08-04 at 09 59 16](https://user-images.githubusercontent.com/6312043/28959667-bc8c621a-78fb-11e7-9f3e-33cabb4e5b00.png)

Looks cluttered, if we could leave like 5 px between them, I think that would look much better.

Thanks!

**Comment by dayures** [comment]
Today is working properly on production
