### ISSUE TITLE
Library CT field description updates - heads up for code + some not showing up

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#321]
Hi,

Based on recent feedback from partners that are now increasingly adding resources to the Portal manually, I have changed some of the descriptions with certain metadata fields for the library. There is more text than I would like, but considering these elements were asked by several people - this explanation is necessary.

I'm not sure what needs to be baked in code or not, so listing all the changes I made here:
- Data provider description edited
- Publisher description edited
- Date of publication edited
- LandVoc concepts edited
- Authors / Editors / Contributors edited
- Corporate author edited
- License edited
- Access to the Resource (= group) added
- Resource language edited
- Image added

The following edits / additions do not show up on the actual edit form, can we make sure they do?

- Data provider
- Access to the resource
- Resource language
- Image

And for the date of publication, can we make sure the text shows up under the actual field (now it is above). Similar to the abstract field. I checked but I'm not sure I can do it myself.

Thanks!

**Comment by lisettemeij** [comment]
Most seem to show up now, thanks!

Only issue is still with the text below the 'Access to the Resource'-group, which is still not showing up. If we could add that, that would be great. Thanks!

**Comment by dayures** [comment]
Today is working properly on production
