### ISSUE TITLE
Land Portal user features (overview of own contributions)

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#323]
For the users of the Land Portal it would be useful to have an overview on their user pages of any of the resources that they have added to the Portal.

These are the only things they can edit and the only way they currently can find these, is if they search for their resources on the Portal (which requires them to know the exact title and everything).

Got this comment from a local partner that is making manual additions, that I think we should take seriously :)

**Comment by lisettemeij** [comment]
Just want to reiterate this that this is a question I've been getting from pretty much every partner that has contributed content.

Definitely a must to have as quickly as possible :)

**Comment by jcr** [comment]
done, see beta user profile page.
1/ block with user 'contributions'
2/ for the said user (if you visit your own profile page) you will also now find a short admin table to let you find/re-edit the content you created.
