### ISSUE TITLE
Land Portal user features (edit menu)

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#324]
The 'Edit' feature is kind of hidden and I'm getting comments from local contributors that they don't know where to find it.
E.g.:
![screen shot 2017-08-09 at 09 35 23](https://user-images.githubusercontent.com/6312043/29114482-c4537324-7cf4-11e7-8eea-5d9024edb812.png)

Possible to make this a bit more prominent somehow?

**Comment by jcr** [comment]
It is now back next to the title of the content (where it was originally)
Probably giving it a color + the new user dash board (which allows you to find and edit you own content) should help mitigate that feeling of not being able to find / edit your content
