### ISSUE TITLE
Organizational teaser image - make sure height and width is always fixed

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#325]
Hi,

The organizational teasers look much better since the latest improvements now that the width is fixed, but I would suggest to fix the height as well. Now, with predominantly horizontal logos (try to add as many verticals as we can, but sometimes there just isn't one!), the box is very small and does not allow enough space to include the organization name in the hover over, e.g.:

![screen shot 2017-08-09 at 11 22 59](https://user-images.githubusercontent.com/6312043/29114592-1e0184d8-7cf5-11e7-85dd-40145d987a9b.png)

Screenshot from: https://landportal.info/library/sources

It would be great if the height could be fixed as well.

Thanks!

**Comment by lisettemeij** [comment]
After a quick chat with Jules wanted to specify the following:

1. If the teasers are going to be changed, I would still recommend having fixed height and weight to make sure that they show up aligned in a grid rather than having a messy group of logos and text;
2. In that regard, it might make sense to have a separate view for search result teasers or related content teasers for organizations, and teasers that show up in a grid like on this library sources page.

Just food for thought, but the main message is anyway that we should at all cost avoid a messy page, regardless  of sizes of logos that are provided. That is something we simply cannot control unfortunately.

**Comment by jcr** [comment]
on the new version, all LLR display (teaser, search and all) keep their image ratio.
