### ISSUE TITLE
Make some arrowd clickable to improve UX

### ISSUE THREAD

**Issue by dayures** [landportal/drupal#326]
![clickable](https://user-images.githubusercontent.com/1654811/29130861-5c320a1c-7d2b-11e7-8c2e-6d56d41550a3.PNG)

For instance, in the collapsable elements of a narrative like in https://landportal.info/book/countries/IND

**Comment by lisettemeij** [comment]
+ 1 this is also on the SDGs boxes, think I mentioned it in a chat one time.

Thanks for putting it on Github, Carlos!

**Comment by dayures** [comment]
This is working today on production
