### ISSUE TITLE
Move the social media icons a bit higher or lower

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#327]
Now when you are looking at the home page, for example the news, and have the news scrolling thing in the center of your screen, the social media icons prevent you from clicking the arrow to navigate right.

![screen shot 2017-08-10 at 16 59 24](https://user-images.githubusercontent.com/6312043/29176873-667b8bde-7ded-11e7-807e-edb06e331b4b.png)

Maybe this can be solved by placing it a little higher or lower?

**Comment by jcr** [comment]
not very-very stylish (yet) but now it shows up at the bottom of pages / content (see beta).
which, I think, is overall much better than the icons we had floating on the right before
