### ISSUE TITLE
Styling on events pages not working

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#329]
The styling for events pages is partially not working.

The bullet points, spacing, etc. are not formatting correctly and everything is just lumped together. See here: 

![image](https://user-images.githubusercontent.com/23736268/29513057-66607892-8664-11e7-8e70-bcbdca9964f0.png)

**Comment by dayures** [comment]
fixed in production

https://landportal.info/event/2017/10/land-and-poverty-conference-2018-land-governance-interconnected-world
