### ISSUE TITLE
URGENT: Allow contributors to publish content (organizational profiles specifically)

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#330]
This is an urgent issue, contributors are not regular users and are given these permissions only after they have been checked if they make good use of the website, fill in good metadata, etc.

So please allow these people to publish their own organizational profiles. It's a nightmare with all the emails I've been getting from local partners not being able to work fast because they require a middle step from us to publish their materials. It takes time even though I try to do it several times a day - but this is just not sustainable.

If this can be fixed right away, that would be great. Thanks!

**Comment by lisettemeij** [comment]
I'm pretty sure this is the link:

https://landportal.info/admin/config/workflow/rules/reaction/manage/workflow_published_contrib/edit/4

**Comment by dayures** [comment]
@jcr The rules has been updated and baked in code in commit https://github.com/landportal/drupal/commit/28d840194dfe9da2073d27ceb33a6d471e379402
