### ISSUE TITLE
On Land debate, when clicking 'back' you return to first page of news, not where you were

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#331]
On the Land Debate, including news, when you click through news, and then click on a news item (or blog), and then click back, it takes you to the first page, not where you were. If you had already scrolled through to the 4th page, you end up back on the first page every time, which is very annoying.

**Comment by silvinabcn** [comment]
Hi @realneilsorensen 
this is solved on https://landportal.org/debate/news
Let me know if this is what you were requesting. Thanks.
