### ISSUE TITLE
Assign maximum height to image in teaser preview

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#332]
Hi,

Some images for a LLR or another content type are kind of long. Can we assign a maximum height to that (maybe fade away like the text?) to make sure this doesn't happen in teasers:

![screen shot 2017-08-31 at 09 40 24](https://user-images.githubusercontent.com/6312043/29912047-94bad79a-8e30-11e7-923d-3e335c4730e0.png)

Thanks!

**Comment by dayures** [comment]
fixed in production
