### ISSUE TITLE
News and Blogs inverted with Library resources and titles reverted to old and bad titles

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#339]
The library resources and the news and blogs continue to be inverted. Also the titles that I changed twice have been reverted to Land Portal related content when I changed it to News and Blogs

![image](https://user-images.githubusercontent.com/23736268/30316094-64cc4d14-97a6-11e7-8880-657a2ff84c58.png)

**Comment by jcr** [comment]
the content title should be set in the configure menu option (block level).
the order option is now permanently fixed (re-open if not)
