### ISSUE TITLE
Country still not required for Mailchimp and Land Portal Sign up

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#344]
As I have mentioned, we need to require country for all who sign up to the Land Portal and for Mailchimp as well. This was the case before and it enabled us to track, at least temporarily and partially, the origin of our users. We need this to be re-established asap. I made it a requirement in Mailchimp again, but I don't know if this has a negative interaction with how you have set it up with regard to the Mailchimp integration.

Also, I get notifications often when approving accounts still that there is a problem with the newsletter registration.

**Comment by jcr** [comment]
also fixed (see other tickets)
