### ISSUE TITLE
Title display when adding resources is bad

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#345]
Hi,

the titles across the Portal have changed in the last weeks/months. Which is great. One thing that is still lacking though is the titles in the forms to add a new CT.

See for example:

http://landportal.info/node/add/landlibrary-resource

![screen shot 2017-09-15 at 15 55 41](https://user-images.githubusercontent.com/6312043/30485648-6598ed12-9a2e-11e7-89fe-919186922a03.png)

The title of "Create a Land Library Resource" is very small and just regular text, especially compared to the label of the title field right below this.

Can we address this by making the titles of the contribute forms a bit bigger or perhaps similarly styled as the headers for content types on the front end?

Thanks!

**Comment by dayures** [comment]
fixed by landportal/drupal-lpbs@17e97af013d8b6278923dfe9e173a7fcfb999cc4
