### ISSUE TITLE
'No preview available' image disappeared

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#350]
Hi,

I just added a LL resource and forgot to add the cover image when I first uploaded. Then I realized that the 'No preview available' image was not showing up, see screenshot:

![screen shot 2017-10-02 at 10 02 10](https://user-images.githubusercontent.com/6312043/31068590-f7bf5276-a758-11e7-875b-a7206c879b3b.png)

It's this link: https://landportal.info/library/resources/n%C2%B0-702a/land-sorrow-human-rights-violations-myanmar%E2%80%99s-myotha-industrial-park (but I've added the cover image by now).

Can we please make sure this shows up again and does not disappear out of nowhere?

Thanks :)

**Comment by dayures** [comment]
This example has not image associated

https://landportal.info/library/resources/0264-8377/small-scale-land-acquisitions-large-scale-implications-exploring-case
