### ISSUE TITLE
When changing the language, you return to the main page

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#351]
Hi,

When you change the language of the interface on the top right screen, you return to the main page.

It would be more intuitive if you would remain on the page where you were, because it's there that you want to see the translation.

Can we fix that? (not particularly urgent, but just to have documented)

Thanks!

**Comment by lisettemeij** [comment]
Same counts when you log in or out. Would be much more convenient if you went back to the page you were visiting

**Comment by jcr** [comment]
All together this is a general behavior problem.
For the comment about login/out - it's partly addressed.
The login is now in a drop down form and reload on the same page you were at.
The logout still send you back to the home page (I believe this is trivial?)

for the language menu on the top right. After few more test the actual behavior is:
 - if the page you look at is translated it brings you to that page
 - if there is no translation it brings you to the home page indeed
