### ISSUE TITLE
Land Debate page mobile device: Overlap of text and images

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#353]
Hi,

On the mobile device, the different information items of an online debate page (dates, status (open/closed) and facilitator profiles seem to be kind of overlapping:

http://landportal.info/debates/2017/responsible-large-scale-agricultural-investment-mekong-region-online-dialogue-9-20
![img_2741](https://user-images.githubusercontent.com/6312043/31722694-0d4cc6d4-b41d-11e7-8373-37839e7ca1c4.PNG)

I don't know what the order should be, but in any case this information should probably not overlap :)

Thanks!

**Comment by jcr** [comment]
fixed, see: https://beta.landportal.info/debates/2017/responsible-large-scale-agricultural-investment-mekong-region-online-dialogue-9-20
