### ISSUE TITLE
Bullet points not showing up correctly

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#356]
At least in organizational profiles, if not elsewhere, bullet points are not showing up correctly:

https://landportal.info/organization/world-bank-group

See two screenshots of editor view and public view: 
![image](https://user-images.githubusercontent.com/23736268/31882868-708b5ff2-b7e8-11e7-90d1-d7f1d0cc501b.png)

![image](https://user-images.githubusercontent.com/23736268/31882769-219f0b6e-b7e8-11e7-8609-2e69a4092f71.png)

**Comment by dayures** [comment]
fixed in production
