### ISSUE TITLE
Add new fields for people profile

### ISSUE THREAD

**Issue by dayures** [landportal/drupal#359]
- Occupation(audience): Closed list
- Sector : Reuse Organization Type taxonomy
- Public email
- Links: (for the Linkedin profile or personal page)

All details are in https://docs.google.com/document/d/1FuBANwPnaOrROlZgKTMwe3W91JXiUq2WaPf56oxoL1I/edit#heading=h.g2ukewvzgn1k

**Comment by jcr** [comment]
+ field to make this profile public or not
+ cleanup "hide my profile" field on the user account

**Comment by jcr** [comment]
done! (if any, migrate preference from user to profile)
