### ISSUE TITLE
Land Library Resource URL - display change?

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#36]
When I upload a Land Library resource, I try to link back to the Resource URL as much as possible and not upload it to the LP.

Only the display doesn't look really good. The Resource URL shows up on the right of the screen - the full url as a link. That looks kind of messy and the URL often disappears on the right side of the screen.

Would it be possible to have the thumb linked to the Resource URL or the title perhaps? Those places would be more logical to me to look for the full document.

Example: https://landportal.info/library/resources/dm-gltn-298070074/urbanization-asia-and-pacific-challenges-responsible-land

**Comment by jcr** [comment]
fixed by using 'Click here to access the resource' as a title for the link
