### ISSUE TITLE
Cambodia narrative--too much space between paragraphs

### ISSUE THREAD

**Issue by ntagliar** [landportal/drupal#364]
I tried to get rid of the space but its not letting me. There should be just one space between paragraphs
<img width="1280" alt="screen shot 2017-10-25 at 5 51 54 pm" src="https://user-images.githubusercontent.com/24232810/32008765-5b63288c-b9ad-11e7-8022-069753e5e120.png">

**Comment by dayures** [comment]
Hi @ntagliar I have updated the HTML code that brought that situation. Is that ok now?

Remember to put a link in the ticket, so it will be faster for us :)

https://landportal.info/book/countries/KHM
