### ISSUE TITLE
Blog authors hidden / obscured

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#366]
Blog authors have somehow been hidden / obscured from posts. See this blog, showing the image of the author cut off on the bottom right-hand side.

https://landportal.info/blog-post/2017/10/women-are-pivotal-addressing-hunger-malnutrition-and-poverty

![image](https://user-images.githubusercontent.com/23736268/32040556-90744c84-ba31-11e7-9438-6b0287cef45d.png)

**Comment by dayures** [comment]
related to #341
