### ISSUE TITLE
Organizational profile - Resource views

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#37]
The resource views on the organizational profiles does not look very good. Only the title of the link shows up (preferably a thumbnail?) and on the link below there is also some other text included (seems to be the first lines of the content text) which probably shouldn't be there:

https://landportal.info/organization/rural-research-development-training-center

**Comment by jcr** [comment]
See also: https://landportal.info/organization/global-land-tool-network

As of today:
 - the teasers for this listing could be improved a bit (org logo)
 - the view filters (on the right) style should also be improved.
 - the line between each element is doubled

**Comment by jcr** [comment]
it should now (on the new version show more properly)
FYI there is 6 to 9 different views for it
 - teaser
 - search results
 - full page
each of them have 2 to 3 ways (sometimes small differences) to show the content.
Very small/Mobile view should also be about ok (though not yet very optimize)
