### ISSUE TITLE
Emails from password change or account creation not received

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#371]
Hi Jules,

I have noted that there is a problem with user passwords and email confirmations. Users are not receiving password change confirmations or reminders or even account confirmations as far as I can tell. There is a serious problem with user accounts. Please look into this immediately.

Neil

Hi Neil, 

This actually brings me to my second point which I was waiting to share: I cannot log into my account. I forgot my password and requested a new one be sent last week. It never was (all folders checked), so I requested again, it still didn't work. I requested a third time earlier today and still nothing.  You may want to check if there is a bug. 

Once I can log in, I will play around to see how to post for future purposes and let you know if I have any questions. 

Many thanks again! 

All the best, 

McKinley

**Comment by jcr** [comment]
ACK, as mentioned in the team chat yesterday, the emails are now properly sent (was a server side issue, hence the green confirmation message on Drupal that emails were sent after those actions).

I'll close this ticket shortly once all the email measure to not end up in spam have been re-checked.

**Comment by jcr** [comment]
closing this as it is now all working as normal. No email sent from our mail server should really arrive in spam folders.
