### ISSUE TITLE
include a table about descriptive stats in the single dataset page

### ISSUE THREAD

**Issue by dayures** [landportal/drupal#373]
@MarcelloLP @jcr

It should be added a similar table that we are using in the Thematic portfolios in the single dataset's page, with descriptive statistics.

Already agreed, the columns would be:

- year coverage
- country coverage (number of countries)
- download button (to download the indicator's data)

For instance in https://landportal.info/book/dataset/fao-asti

**Comment by jcr** [comment]
done, see beta
