### ISSUE TITLE
LL: Place LandVoc+geographical focus items next to description again

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#375]
Hi,

On the Land Library form  (https://landportal.info/node/add/landlibrary-resource), the LandVoc fields and geographical focus fields used to be on the right side of the abstract / description field. With one of the recent changes, as I mentioned on the chat, this has suddenly changed and is now below each other:

![screen shot 2017-11-02 at 09 44 46](https://user-images.githubusercontent.com/6312043/32317035-c1581516-bfb2-11e7-9259-395ec7ecec0b.png)

Now, as I mentioned on the chat, you have to continually scroll up and down to find the information (because these tags information, you usually get from the description / abstract) and enter it.

Can we please change that back to how it was (in two columns)? Same counts for the image, that is now randomly between Title and Subtitle (two fields that obviously need to stay together, not with something else randomly placed in between).

If this is a problem for consistency sake for the other parts of the website, I would suggest to change everything back to how it was (it used to be consistent and very convenient).

Thanks!

**Comment by lisettemeij** [comment]
This does seem to be the way it's displayed in 'edit a LL resource':

https://landportal.info/node/62876/edit
![screen shot 2017-11-06 at 16 40 47](https://user-images.githubusercontent.com/6312043/32449222-4b93101c-c311-11e7-84f6-94ce95ad15cc.png)

And see here again a blank form to create a LL resource (https://landportal.info/node/add/landlibrary-resource):

![screen shot 2017-11-06 at 16 43 09](https://user-images.githubusercontent.com/6312043/32449349-9b6caada-c311-11e7-91b2-7b33a9ab2f32.png)

Totally confused!

**Comment by lisettemeij** [comment]
For the record: the first image (as it's in the editing menu now) is how it should all look!

**Comment by jcr** [comment]
done and done (see beta ;)
