### ISSUE TITLE
Teaser images mobile view should be rendered better (text)

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#376]
Hi,

Was just looking at the SDGs section on my phone (6s, fairly standard size) and the teasers for related content are really squished, mainly the text - which is reduced to one letter per line.. which basically means it’s not readable:

![e1a7ca84-cd94-42e6-a05c-f6c6d4346aec](https://user-images.githubusercontent.com/6312043/32342451-b178969a-c000-11e7-8a15-189672ef7fd9.png)

This should probably be fixed, right? This is the link: https://landportal.info/book/sdgs/142/sdgs-indicator-142

Thanks!

**Comment by jcr** [comment]
could use more design work but the display issue is fixed
see https://beta.landportal.info/book/sdgs/142/sdgs-indicator-142
