### ISSUE TITLE
Organizational profiles: acronyms

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#38]
When adding organizational profiles I'm noticing that a lot of the organizations that have an often-used acronym, have just the acronym as a title or between brackets behind the full name, e.g.: Global Land Tool Network (GLTN) -> https://landportal.info/organization/global-land-tool-network-gltn-0

Ideally, the field of the acronym when adding an organizational profile would contain the acronym and the title would be the full title, to avoid any confusion.

However, when you do it this way, the organization doesn't show up in the search results on Drupal if you search for the acronym only. Or, for example, when you try to fill in a Provider when adding a LL resource and you use the autofill. 

Is there any way that we can expand the search options that it also includes the added acronyms field in the organizational profile?

**Comment by jcr** [comment]
fixed in production (needs to be baked in the CT features)
now you can update the organization profiles :)
