### ISSUE TITLE
Blog authors appearing incorrectly

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#388]
Blog authors are appearing incorrectly, with a mixture of their user name and first name. The correct way would be to include First and Last name and to hide the user name.

![image](https://user-images.githubusercontent.com/23736268/33083759-87dc68f4-cee0-11e7-8c1e-68ef24cdf727.png)

**Comment by jcr** [comment]
Fixed for all accounts.
A number of (mostly old) profile / user account were potentially impacted with this bug (1/3).

Carlos noted (thanks for the help) that many of them related to potential 'spam' or 'bot' accounts (discuss about accounts policies, curating them, disable or cancel after a certain times if there are no contrib or login.... ?)
