### ISSUE TITLE
Land Library Resource display thing

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#39]
With a LL resource that was imported from the legacy portal, there is a field on the right that says "replaces" and then the URL at the legacy LP, see for an example: https://landportal.info/library/resources/forest-management-and-use-kyrgyz-republic-development-potential

Can we remove this view? Doesn't seem very necessary to know for the user.

**Comment by jcr** [comment]
hidden for now, will likely disappear during the field cleaning.
(once we merge existing information somewhere > at least in a revision note)
