### ISSUE TITLE
New autocomplete form - make possibility of multiple entries clearer

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#391]
Hi,

With the new autocomplete form it is great that newly added nodes are recognized right away, but there is one thing that can be improved in this form. It is not clear at all that multiple entries are possible, see the screenshot below for example:

![screen shot 2017-11-29 at 14 02 50](https://user-images.githubusercontent.com/6312043/33376515-47759f36-d50e-11e7-9a2e-847dce277330.png)

I understand help text could be an intermediary solution, but I don't think that goes far enough.Let's face it - people often don't read that.
 
It would be great if we could match the way the taxonomy entry fields work, in that when you have your cursus next to a value that you put it - it suggests to you that you can enter more (see below). Whereas as you can see in the screen above, I can simply enter letters there and it is not clear that I can put in more after that. You have to clearly to a comma first, and then you start typing and only after a while it gives you options. It would be great if that can be done more intuitively and similar to the concepts as seen below:

![screen shot 2017-11-29 at 14 07 44](https://user-images.githubusercontent.com/6312043/33376666-e8f40b5e-d50e-11e7-8fa6-19e87c066c9e.png)

Another great thing about this option is that the field expands as you put in more, so you always have the overview of what you put in. The current node-selection box constantly goes back to the beginning, so you only see your first input, and you constantly have to move your cursor to the end to enter new entries.

Would be great if this can be improved, then the new autocomplete form is perfect.

Thanks!

**Comment by lisettemeij** [comment]
When you've entered one value, you can't continue typing, unlike with the concepts.

You have to purposely set your cursor at the end of the previous value, enter a comma and then enter the new value. 

It just takes a lot more time than the simple intuitive taxonomy tagging. Also in terms of consistency it would be great if these autocomplete fields would simply work the same.

**Comment by jcr** [comment]
where you have multiple org possible there is not an 'add another item' button.
there is also some new add / edit link (close to the field) that lets you create /edit org directly there (to be tested more)
I close this issue as the problem described there is now solved by only 1 organization per field (which is overall the right UI for this)
