### ISSUE TITLE
Make Beta titles links to the different sections

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#395]
Hi,

Can we make the titles of the different sections links to those different sections?

E.g.: https://beta.landportal.info/

![screen shot 2017-12-14 at 10 00 51](https://user-images.githubusercontent.com/6312043/33983957-3f696f44-e0b6-11e7-8ef6-f7442e70a861.png)

That countries links to the countries landing page, issues to the issues landing page, etc.

Thanks!

**Comment by jcr** [comment]
This functionality is now available in the regular block configure screen.
As those have been done (thanks Lisette!) and it's not like there is going to be a lot more, let's not automate this.
