### ISSUE TITLE
Organizational profile logo size

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#41]
Is it possible to force the uploaded logo into a specific size that looks good on the site?

For me, when adding tons of new organizations, it's really a pain to look for specific sizes. But it's mostly relevant for when users would add their own organizations - we want it all to look good regardless to what they upload, right?

See this for example: https://landportal.info/organization/us-department-state. Doesn't really look good.

**Comment by jcr** [comment]
On top of that there is obviously an issue with the left/right columns float (the org title should be at the same level as the logo.

**Comment by aostroverkhov** [comment]
@jcr ready on Dev - https://dev.landportal.info/organization/us-department-state

**Comment by jcr** [comment]
fixed and working
