### ISSUE TITLE
Certain boxes editing user profiles appear incorrectly

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#412]
Location, country, name, city, etc. are not aligned correctly when editing user profiles.

https://landportal.org/user/19474/edit?destination=admin/people/moderate

![image](https://user-images.githubusercontent.com/23736268/34479364-91ee474a-efa6-11e7-88d9-5a49ccdec1c5.png)

**Comment by jcr** [comment]
fixed
