### ISSUE TITLE
Spacing / Styling of events less than ideal, especially regarding metadata terms

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#422]
The relationship of the metadata to the events pages is not very good, and also titles for all the metadata are lacking. It should say Geographical focus: before geographical terms Thematic focus: before thematic terms and Related LandVoc Terms before related terms.

As, the positioning is really questionable and confusing, and the styling overall needs some attention.

https://landportal.org/event/2018/01/land-tenure-and-property-rights-mooc-30

![image](https://user-images.githubusercontent.com/23736268/34823004-286814f2-f6c9-11e7-8675-51cbd4fa5764.png)

**Comment by silvinabcn** [comment]
hi @realneilsorensen 
I'm closing this issue because it seems that this already has been changed in the site. Please re-open the ticket if there is still changes to be done. Thanks.
