### ISSUE TITLE
Missing space between title, first name and last name of a profile

### ISSUE THREAD

**Issue by dayures** [landportal/drupal#425]
This issue appears in the teaser view and in the normal view of a profile (through user)

For instance in:
https://landportal.org/debates/2018/making-rangelands-more-secure
https://landportal.org/users/jules

It could be related to the use of "display: inline-block" for the classes ".profile2-main .group-name .field"

![captura](https://user-images.githubusercontent.com/1654811/34995906-38fb45a6-fad8-11e7-9618-7287bc91ceb2.PNG)

**Comment by realneilsorensen** [comment]
Please address this asap.

**Comment by lisettemeij** [comment]
Neil reported this again on July 6th as not being fixed:

--

I have reported this bug probably a dozen times but it has never been fixed. There is no space between the first and last name of users on their profiles and everywhere their names appear, as this screenshot shows:

![42373540-7c22ef1e-8115-11e8-92e1-6272cee051b1](https://user-images.githubusercontent.com/6312043/42374707-4a7df978-8119-11e8-8c23-8e04ef95a3c7.png)


Please include a space between the first and last names. See example here: https://landportal.org/users/frits-van-der-wal-0
