### ISSUE TITLE
unified/update list of items comma separated

### ISSUE THREAD

**Issue by dayures** [landportal/drupal#426]
https://landportal.org/debate/debates

![captura](https://user-images.githubusercontent.com/1654811/34996918-575f10a6-fadb-11e7-8914-56ba3b7562e9.PNG)

**Comment by jcr** [comment]
fix on drupal-lpbs
`@@ -68,7 +68,7 @@ fieldset.date-combo {
         .field-label {
             display: none;
         }
-        .field-item {
+        .field-items {
             @include field-glyphicon($glyphicon-user);
         }
     }
`
