### ISSUE TITLE
Ajax error when adding related content to SDGs indicator pages.

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#427]
The functionality of adding related content to SDGs pages has changed. That aside, it is not working. I tried to add Chris Penrose Buckley's blog to indicator 1.4.2, but I get this error when I do the title search.

https://landportal.org/node/52264/edit

![image](https://user-images.githubusercontent.com/23736268/35034367-33439780-fb6e-11e7-8896-61f21404a55f.png)

**Comment by jcr** [comment]
fixed. raised our php limit to 1500 vars/post which was apparently causing the issue in this view.
(for the record
https://www.drupal.org/forum/support/module-development-and-code-questions/2013-06-10/why-is-drupal-sending-ajax_html_ids )
