### ISSUE TITLE
on the discussions page, I don't see the total number of comments for each discussion

### ISSUE THREAD

**Issue by ntagliar** [landportal/drupal#428]
On the landportal.info platform, we could see if there was, for instance 57 comments for a discussion, but .org does not have this feature

**Comment by jcr** [comment]
For the record, discussions, we have basically 2 teasers view now:
 - a short vertical one - as seen on the Home page.
 - a 'regular' teaser one
https://landportal.org/debates/2017

the last one shows the 'number of comments' and 'add comment' links as intended
