### ISSUE TITLE
Author/contributor view in Land Library

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#43]
Is there any way to change the view of the author/contributor in the Land Library? Currently they are a 'person': https://www.landportal.info/library/resources/training2010/training-course-landproperty-and-housing-rights-muslim-world, the teaser of which is set to 'h2', which makes the text ridiculously huge compared to the summary or even the title of the resource.

I'm also not sure about whether we should want author/contributors entered as a 'person' at all. If you want to add an author manually in a LL resource, you have to 'create' a person-page, which I'm never really comfortable with, because people can comment on it and such (e.g.: https://www.landportal.info/person/2016/03/amyn-mussa)

Can't we just have the authors and contributors listed as text? Now I either leave the authors out or put them in the description page. Only when an author has a user profile on the LP do I add them here.

**Comment by jcr** [comment]
cleared ;)
