### ISSUE TITLE
Connected organization doesn't show up on profiles

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#448]
Connected organizations no longer show u p on the profiles of individuals.

See this example:

https://landportal.org/users/makko-sinandei

![image](https://user-images.githubusercontent.com/23736268/38139611-869df43e-3430-11e8-926b-c23a76a2cb77.png)

**Comment by lisettemeij** [comment]
Closing this one as it's the same as https://github.com/landportal/drupal/issues/450

That one has a bit more description to it what it should be, so that's why I'm closing this one :)
