### ISSUE TITLE
User registration

### ISSUE THREAD

**Issue by jcr** [landportal/drupal#45]
On the form / page 
- Improve form design (make it more compact / styled , remove ugly duplicate fields for "links"
- Allow user to subscribe to Land Portal bulletin/newsletter in the language they want + multiple?

**Comment by jcr** [comment]
Newsletter subscription functionnality Ok - style can be better.

With the new style (2.3) the select inputs don't look good (style partly showing up?).
The other input fields style should be consistent.
See: https://landportal.info/user/register

**Comment by aostroverkhov** [comment]
@jcr corrected the styling a bit, please check - http://beta.landportal.info/user/register
Not sure though what to do with "links" fieldset, should we just hide it on this form or remove the field completely, what do you think?

**Comment by jcr** [comment]
I think we will "re-design" this whole process in the next milestone

**Comment by jcr** [comment]
register form had a quick polish / makeup in the new version
