### ISSUE TITLE
Images still hosted on landportal.info / redirect not functioning correctly

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#451]
Several images on the Land Portal are not loading correctly and seem to be hosted still on landportal.info:

https://landportal.org/node/43948/edit

See the screenshot below.

Also, there is no security certificate for landportal.info, which seems to be creating a number of problems, perhaps also with the redirect.

![image](https://user-images.githubusercontent.com/23736268/39619024-841b03de-4f86-11e8-8907-3d38a155ca7b.png)

**Comment by asanchez75** [comment]
Fixed. the images are displayed correctly now. 
See
https://landportal.org/about/foundation/board
and
https://landportal.org/about/the-people.
However, the warning messages are still displayed. I will check why.
