### ISSUE TITLE
Icons on front page disappeared

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#458]
Hi,

The icons on the front page seem to have disappeared and replaced with blue box-frames:

<img width="1487" alt="screen shot 2018-05-16 at 15 52 09" src="https://user-images.githubusercontent.com/6312043/40121461-ec551954-5921-11e8-920b-41b2ef3ac891.png">

This is on the home page. Can we bring the icons back?

Thanks!

**Comment by asanchez75** [comment]
fixed
