### ISSUE TITLE
SOLR search seems to work with older version of content

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#469]
Hi,

When you use the website-wide SOLR search, you do not seem to access the latest version of the database. 

For example, the Library has over 48,000 resources right now (https://landportal.org/admin/content/library), but in the SOLR search, it only registers 47,000 (https://landportal.org/admin/reports/apachesolr/landlibrary_search).

Also, when you look for a recent organizational profile (exact same name), it does not show up in the SOLR search, e.g.:
https://landportal.org/search/site/Online%20Burma%252fMyanmar%20Library
https://landportal.org/organization/online-burmamyanmar-library

Does the SOLR database need to be updated somehow? How does this work?

Thanks!

**Comment by asanchez75** [comment]
it will be done during this weekend because the solr service can be down. 
I need to detach the server where solr is running to recover the password of the server.

**Comment by asanchez75** [comment]
It has been fixed. The mysql user (database level) was not authorized to access remotely from the IP of the two Apache web servers.
