### ISSUE TITLE
Search options topics

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#47]
I've mentioned this before when Alexey delivered the first 'sprint', which I guess hasn't been addressed yet.

I really like the new search view, looks a lot better than it was before: https://landportal.info/search/site/

However, I still want to stress that looking for specific topics is not ideal. People will want to filter their research to more than just one topic. We need to show this search option differently... perhaps also auto-complete in a form or something.

**Comment by jcr** [comment]
now it behaves like that
