### ISSUE TITLE
Domain authentication for Mailchimp needed

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#475]
The following needs to be added to the DNS of landportal.org for us to be able to send emails from landportal.org email address. 

Please update the DNS as follows:

Authenticate landportal.org with MailChimp by modifying your domain's DNS records. These changes allow your campaigns to appear to come from landportal.org, instead of from our servers. After you've made the required DNS changes, please wait 24-48 hours for the changes to propagate. Why should I do this?

DKIM: Create a CNAME record for k1._domainkey.landportal.org with this value:
dkim.mcsv.net
SPF: Create a TXT record for landportal.org with:
v=spf1 include:servers.mcsv.net ?all

![image](https://user-images.githubusercontent.com/23736268/42155861-d1058926-7de9-11e8-9236-8c5f6205fa07.png)

**Comment by asanchez75** [comment]
done. please try

**Comment by asanchez75** [comment]
done. please try
<img width="1021" alt="screen shot 2018-07-24 at 8 52 34 pm" src="https://user-images.githubusercontent.com/383566/43159763-9235e294-8f83-11e8-805e-73e107001138.png">
