### ISSUE TITLE
No space between first and last name of users everywhere on the Land Portal

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#476]
I have reported this bug probably a dozen times but it has never been fixed. There is no space between the first and last name of users on their profiles and everywhere their names appear, as this screenshot shows:

![image](https://user-images.githubusercontent.com/23736268/42373540-7c22ef1e-8115-11e8-92e1-6272cee051b1.png)

Please include a space between the first and last names. See example here: https://landportal.org/users/frits-van-der-wal-0

**Comment by lisettemeij** [comment]
I'm sorry, I am going to close this issue as it was already reported before by Carlos:

https://github.com/landportal/drupal/issues/425

Will copy-paste your inputs to there, Neil. But as Jules replied to that and apparently had something ready for release there, think it's better to refer Adam to that one, as he might be able to build on what Jules already did to address this.
