### ISSUE TITLE
When creating land portal users they do not receive email confirmation with account details

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#477]
Users are not receiving email notification of the creation of an account for them, even when the 'notify user of new account' is clicked. This is in addition to the already mentioned problem that the connection with the Mailchimp is not working.

![image](https://user-images.githubusercontent.com/23736268/42455959-f0d32362-8393-11e8-9bab-f9b546629d25.png)

**Comment by asanchez75** [comment]
Fixed. A docker container along with a drupal module were added to send emails.
