### ISSUE TITLE
Images not being captured by social media / search engines

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#478]
Images from the Land Portal are not being picked up by social media sites or search engines. They used to but stopped a while ago. 

When posting the associated images no longer are grabbed by relevant social media sites, which is quite problematic.

Example: 

![image](https://user-images.githubusercontent.com/23736268/43077763-c08b527e-8e88-11e8-9eb4-6e0e27e8839c.png)

**Comment by asanchez75** [comment]
I do not see the problem. See this screenshot.
<img width="720" alt="screen shot 2018-07-23 at 5 52 05 pm" src="https://user-images.githubusercontent.com/383566/43088010-7665d7b4-8ea1-11e8-817a-36c0218be15c.png">
