### ISSUE TITLE
Image in importer is not working as expected

### ISSUE THREAD

**Issue by dayures** [landportal/drupal#483]
Re-running the importer "olc_json_importer", the image field is not set properly, so old items lost the image. 

There are some messages in the log like 
`Invalid enclosure <em class="placeholder">private://feeds/olc-thumbnail.png</em>`
But the file is there with the same permissions than, for instance, resource-equity (which feed importer was run this same week)

**Comment by dayures** [comment]
The previous time when this importer was run was February 2017, and as far as I remember, there was not such log message.

**Comment by asanchez75** [comment]
OK, does this message appear in the Feeds UI? if yes, may you tell me which importer is to try by myself?  I suppose that the only thing I should do is just run the "import" button to see the erro messages. BTW, where is the datasource?. Can you show me un cherry-pick or un diff between git the commit from February 2017 and the current one?

**Comment by asanchez75** [comment]
Sorry, I just read the name of the importer = olc_json_importer

**Comment by lisettemeij** [comment]
Hi guys, just to jump in here. I posted something about this thread in our LP Website chat, in terms of prioritization of issues to address. Would appreciate it if you guys could jump in there, thanks ;-)

**Comment by asanchez75** [comment]
The boss (after Laura) has spoken (c'est une blague). Amen :)

**Comment by dayures** [comment]
The message appeared in https://landportal.org/admin/reports/dblog (not in feeds UI).

Please, find attached a sample json (zipped) to test (already used for testing, so the image is not there).

[sample.zip](https://github.com/landportal/drupal/files/2392743/sample.zip)

**Comment by lisettemeij** [comment]
Ahh hahahahaha. Sorry I'm such an annoying person (A)

**Comment by dayures** [comment]
Fixed tweaking Drupal
