### ISSUE TITLE
Redirections using the uuid are not working

### ISSUE THREAD

**Issue by dayures** [landportal/drupal#486]
http://data.landportal.info/library/resource/f7125bd2-c5be-4100-b097-4e063c0bb0fa
http://data.landportal.info/news/e56fb7e8-d596-4c56-bf3c-9bd01aeb03c6

previously, they worked using .htaccess (source file in bitbucket private repository- shared by email)

**Comment by dayures** [comment]
For example:

- http://data.landportal.info/library/resource/f7125bd2-c5be-4100-b097-4e063c0bb0fa
- redirected to https://landportal.info/node/f7125bd2-c5be-4100-b097-4e063c0bb0fa 
- later, due to Drupal configuration, redirected (finally) to https://landportal.org/library/resources/lu%C3%ADsa-borges-andr%C3%A9-calengo-com-beatriz-galan-antonieta-coelho2011/gui%C3%A3o-para

**Comment by asanchez75** [comment]
fixed,  please closed the the ticket after your review.

**Comment by asanchez75** [comment]
do not try yet, there was an issue related with redirections

**Comment by dayures** [comment]
Thanks!
