### ISSUE TITLE
Display search results Land Library

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#49]
Hi,

Can we adjust the display of the search results in the LAnd Library?

The thumbnails are placed above the resource title, which makes it confusing as to which resource the picture belongs to. Possibly to align it on the left of the text information of the same resource?

Can we have a line between one resource and the other to make the distinction between the different resources? Similar to the way news items are divided on this page: http://landportal.info/debate/news ?
Antonella mentioned that that is a CSS issue, so not for her to fix.

Thanks!!

**Comment by jcr** [comment]
should be fixed.
The search results is now using a 'normal' / regular rending method.
The view is now entirely different and display proper fields- cleanup is still in the process though.
