### ISSUE TITLE
QTR Admin (LEGEND CLST) unable to administer QTR content

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#500]
In a call with the new administrator of the QTR page (https://landportal.org/partners/quantifying-tenure-risk) for the Legend CLST we discovered that they do not have the ability to associate content with the outputs page or to add featured content to the landing page.
See screenshot from new CLST admin's computer:
![issueqtrpageassociatingcontent](https://user-images.githubusercontent.com/23736268/52963446-0b5dee80-33a0-11e9-96c4-c733630ee6e3.png)

As they have the same admin access to the page in principle as the Land Portal, they should see this instead and be able to associate content: 

![image](https://user-images.githubusercontent.com/23736268/52963592-81625580-33a0-11e9-9c96-60b2d834eeee.png)

and this:

![image](https://user-images.githubusercontent.com/23736268/52963672-b2db2100-33a0-11e9-9fb0-376b0f6c2279.png)

**Comment by asanchez75** [comment]
this has been fixed
