### ISSUE TITLE
Language selector does not work on mobile phones

### ISSUE THREAD

**Issue by silvinabcn** [landportal/drupal#502]
Language options in Main Menu do not work in Android or iPhone telephones.
The site should always load the  current page in the selected (by the visitor) language.

**Comment by silvinabcn** [comment]
To do: Analyse DIVS when changing resolution

**Comment by silvinabcn** [comment]
Hi @asanchez75 
you are right: the languages get hidden behind the content area. Is this something we can solve through CSS? I tested changing the z-index on the browser developers' tool but it doesn't seem to fix the issue. Please let me know what you think.
Thanks.

**Comment by asanchez75** [comment]
This is fixed.

<img width="407" alt="Capture d’écran 2019-04-01 à 06 57 08" src="https://user-images.githubusercontent.com/383566/55304397-988a6d80-544b-11e9-96e1-4457ca3ab3dc.png">

**Comment by silvinabcn** [comment]
thanks @asanchez75 
Now It works OK also in iPhone.
