### ISSUE TITLE
OurLandOurStories Not Appearing!!!!!

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#508]
Non of the stories on OurLandOurStory stories are appearing! See here: https://www.landportal.org/campaign/2019/03/can-technological-revolution-prompt-land-rights-revolution-mozambican-land-rights
There is a note saying 'node links go here'. 

https://www.landportal.org/ourlandourstory

Stacey uploaded the stories in time for the launch on the 12th of March. I had these stories online and showed everyone how it worked on stage, and it worked. What happened? This is VERY urgent, as the stories and campaign have been widely promoted by us and our partners.

![image](https://user-images.githubusercontent.com/23736268/55067107-65c52b80-507f-11e9-8269-b150214edb99.png)

**Comment by silvinabcn** [comment]
It works OK in DEV.
Content is both on PROD and DEV.
display and panelizing seems to be the same on both sites.

**Comment by realneilsorensen** [comment]
So what is the solution?

**Comment by silvinabcn** [comment]
fixed. closing the issue.
