### ISSUE TITLE
Tag display 'Resource type' in listing looks ugly

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#55]
Hi,

The tag display of a resource type is really ugly in a search result. The tag has a blue background, but the original brown one shows up behind that in the whole width of the text block.

See here: https://landportal.info/topics/contract-farming

**Comment by jcr** [comment]
I believe this is already improved. The LLR (and many other) needs a proper design.
The "tags" / "terms" elements of the website also need a special attention of their own as they are important piece of information across the portal.

**Comment by jcr** [comment]
Thanks to Alexey work (ironic hein), they hid all the tags and fields while hardcoding all the content rendering. So now, there is almost no information or incentives about the resources before you click them. This tag doesn't show up in listings anymore so does the landvoc concepts.
