### ISSUE TITLE
Organizational profile - some fields not showing up on page

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#56]
Neil noticed some of the fields in the Organizational profile form are not showing up:
- Contact person (this used to be on the bottom before, but somehow seems to have disappeared. Did this happen after adding the resources and stuff?)
- Organization address (is under Location in the form, a folded menu).
- Organizational type (I believe this was deleted because Laura disliked the brown tag?)

Can we make a space for this? (especially the organizational address would be a priority I suppose)

**Comment by jcr** [comment]
Since the summer and the release of the new LB, there was a ton of template hardcoded  (thanks Alexey team!). This is now fixed in the next release and we can re-use the "manage display" core drupal functionality (and it will work as expected).
