### ISSUE TITLE
Overarching categories, not domains

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#58]
Can we change the name of the Overarching Categories back please instead of Domains? We never agreed on Domains and it is a bit of a confusing name. Overarching Categories is much clearer.

Thanks!

**Comment by jcr** [comment]
I started updating those taxonomies names a bit everywhere.
It would be useful to comment on this ticket and put the URL each time you find one that needs to be renamed.

**Comment by lisettemeij** [comment]
Real quick reply: I will look it up,l and give you urls, but can't we also
change it on the back end in Drupal? It's a bit confusing. So domains->
overarching categories, themes are fine and then topics-> concepts?

**Comment by jcr** [comment]
been cleaned already, reopen if you have specific place where it still appear
