### ISSUE TITLE
breadcrumbs (was: Double the title in organizational profile)

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#59]
The name of the organizational profile shows up twice on the page. Once in the title, but also just below the navigation bar in a grey bar. Can we delete that last bar?

E.g.: https://landportal.info/node/30222

**Comment by dayures** [comment]
The grey bar is the "breadcrumbs" of the website. I will take into account in the UX review

**Comment by jcr** [comment]
breadcrumbs should probably 'only' show (not the node/element title).
> home > organization
This comment is valid for about every sections on the portal

They could be hidden on the whole site - that is a separate question.

**Comment by jcr** [comment]
I guess the solution here was no more breadcrumbs, no more problem!
(this is awful for UX and accessibility , specially given that our menus/submenus aren't necessarily  self-explanatory to figure out where you are).
