### ISSUE TITLE
Possibility for override delete option despite mandatory fields blank?

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#60]
Is it possible to add the possibility for certain (restricted amount) of users of the LAnd Portal to delete an organization for example even when the mandatory fields have not been filled in yet? Now you have to first fill in the mandatory fields before you're able to delete a resource. This has become quite a time-consuming annoyance when cleaning up the organizational profiles, which are hundreds, so altogether deleting empty ones that were imported from the legacy portal takes more time than it should.

This is also an issue for example with the LL resources. In importers, not all the mandatory fields are always filled in (for example with GLTN, language was sometimes missing if the language wasn't available in the list. It happened with the Arabic ones for example). When enriching the metadata, Natalia and I had to select a language anyway (even when it wasn't Arabic) to be able to make changes to the resource metadata.

Is it possible to add an override option for this? I'm thinking only a very restricted group, so not even all LP team members. Perhaps only give it to the admin account and people could log in there? (Neil or me for example).

**Comment by jcr** [comment]
sounds like a creepy/weird drupal behavior (indeed why fill out mandatory fields of something you want to delete) .
What if you use the delete action from the content view table ?

**Comment by jcr** [comment]
I think the right thing is to use the admin actions from the overview table, not the edit node.
I am closing this as there is very little chances we will change Drupal behavior on this.
