### ISSUE TITLE
Land Library re-use page doesn't work anymore

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#62]
Valeria notified Laura that the re-use page in the Land Library is not working anymore, those queries. She said they used to work before (she tested those intensively) when she delivered the product. 

Personally I haven't ever used it so I don't know if it ever worked before. But is there something that is done lately that has affected this? Or did it never work? 

Could you please let me know?

**Comment by jcr** [comment]
fixed (see https://github.com/landportal/drupal/issues/65)
