### ISSUE TITLE
Library data reuse page not working

### ISSUE THREAD

**Issue by valeriapesce** [landportal/drupal#65]
The Land Library Data reuse page is not working as it used to. The buttons to copy the queries in the main textbox work, but then the button to execute the query doesn't.
http://www.landportal.info/library/reuse

I checked the original version of the source code of that page that I had and I noticed a couple of things:

1) A hard-coded query has been added at the beginning of the page, a test perhaps:

```
<p><a href="
http://landportal.info/sparql?default-graph-uri=&amp;query=PREFIX+dc%3A+%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F%3E%0D%0APREFIX+bibo%3A+%3Chttp%3A%2F%2Fpurl.org%2Fontology%2Fbibo%2F%3E%0D%0APREFIX+skos%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23%3E%0D%0Aselect+distinct+%3FTopicURI+%3FName+where+%7B%0D%0A+%3FTopicURI+a+skos%3AConcept+.+%0D%0A+%3FTopicURI+skos%3AprefLabel+%3FName+.%0D%0A+%3FTopicURI+skos%3AinScheme+%3Chttp%3A%2F%2Fdata.landportal.info%2Fvocabulary%2F5%3E%0D%0A%7D%0D%0A&amp;should-sponge=&amp;format=text%2Fhtml&amp;timeout=0&amp;debug=on
" target="_blank">Test first query and get result</a> (html)</p>

```

This is not the reason why the page is not working of course, but a hard-coded query with no explanation on such a page doesn't make much sense.

2) The text filter had been changed to Full HTML. This is not a big problem either but there is a risk that if a non-developer edits the page in the text editor he may inadvertently delete some part of the hidden code.

3) Now to the real problem: the original source code that I have points to the dev SPARQL endpoint and loads scripts from the dev environment (it had been created in the dev environment) and it works. I attach the HTML code used for the tests before copying the code to the Drupal page. (The button that executes the query works, although the triple store in dev is empty so you only see the empty tags of the query results.)

So I was wondering if the problem could be that something is different in the live environment compared to the dev/test environment.

I remember that when the page was ported to the live environment it worked. We did extensive tests on it because it's an important page and it was a test for the whole Linked Data layer.
So perhaps something has changed in the live environment?
It could be the triple store / SPARQL endpoint configuration or perhaps a problem with Ajax (the query is sent with an Ajax call). Or some consequence of the fact that the live environment is behind https?

I hope this helps.

Valeria

[ll-reuse-dev.htm.txt](https://github.com/landportal/drupal/files/250292/ll-reuse-dev.htm.txt)

**Comment by jcr** [comment]
fixed.
it was working on http and not https.
the problem was that the javascript in the page that was trying to access the http://..../sparql when on an https page resulting in ajax not issuing the query.
I changed the hidden input for the endpoint to use a relative path, this way it have multiple benefits:
 1/ allow https or http 
 2/ will query "/sparql?XXXX" this way it will work no matter what environment and /sparql can be configured on per host/environment basis.
