### ISSUE TITLE
New autocomplete form - did we lose the synonym suggestions?

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#66]
I was adding concepts and noticed that for capacity building and capacity development, for which used to be a synonym suggestion, there is no synonym suggestion anymore.

Does that mean that options is disabled completely?

**Comment by jcr** [comment]
should be back , all the fields in the Topics and Regions group [1] are set to " Synonyms friendly select list	"

[1] https://landportal.info/admin/structure/types/manage/news/fields
