### ISSUE TITLE
Geographic focus field entries lost in Land Library (GLTN resource)

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#67]
I don't know when this happened, but when adding the OAs and Themes to the GLTN resources (the metadata of which Natalia and I enriched one by one), the geographic focus got lost for most of the resources. I am manually adding them again, but this is really not something that we want to have happen. I hope it's not the case for other resources as well, because that would be horrible.

For now, I can't find out a pattern (not only for 'global' or a specific country), but seems pretty random.

Any idea what happened??

**Comment by jcr** [comment]
fixed
