### ISSUE TITLE
User registration, mailchimp suscription

### ISSUE THREAD

**Issue by jcr** [landportal/drupal#69]
When creating a new user account, after the form submission I get a Warning:

> There was a problem with your newsletter signup: FNAME must be provided - Please enter a value

I believe they are not added to the Newsletter?

How can we re-add/sync the new accounts that were created since then?

**Comment by aostroverkhov** [comment]
@jcr this error is already fixed on Dev site, please check. If all is correct - will need to push our latest commits to the Live site.
As for users sync - will probably have to write a custom script to go through Drupal users and sync them to Mailchimp. However now it's not really clear how to determine which users should be added to Mailchimp? Or should all Drupal users be synced to Mailchimp?

**Comment by jcr** [comment]
Sorry for the late comment.
There is much likely no need to sync all users from Drupal to MC (at least not now / in this issue).
Users have a subscription option when they register, when they have an active account they can register at https://landportal.info/fr/user/XXX/mailchimp
