### ISSUE TITLE
Overarching Categories + Themes should be added to news form

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#71]
The Overarching Categories + themes should be added as fields to the news contribution form. Currently I only see them in the LL, but this is something that should be applied to the whole website.

**Comment by jcr** [comment]
all CT have been updated with the latest "Topics and Regions" group, which include the 4 fields,

geographical focus
Related concepts
Overarching
Themes and use the nice autocomplete/select ex: https://landportal.info/node/add/news
