### ISSUE TITLE
Search result preview -> source / provider not mentioned

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#74]
Hi all,

In the search result preview (e.g.: http://landportal.info/library/search?f[0]=im_field_related_topics%3A3703&f[1]=im_field_related_topics%3A3703) the organization (provider) is not mentioned. See the attached screenshot.
<img width="1280" alt="screen shot 2016-05-25 at 17 28 25" src="https://cloud.githubusercontent.com/assets/6312043/15545976/76a086a0-229e-11e6-8adf-c2bc30e466eb.png">

I think it would be good to include (with letters, similar and below "Publication date").

**Comment by jcr** [comment]
fixed
