### ISSUE TITLE
4000 pages on Drupal not indexed

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#75]
Hi all,

Neil emailed the team with the following: 4000 pages on Drupal are not indexed.

![unnamed](https://cloud.githubusercontent.com/assets/6312043/15546051/bc0cb1aa-229e-11e6-8946-54bed24e3e88.png)

He asks to check it and fix :)

**Comment by jcr** [comment]
https://landportal.info/admin/config/search/settings
(on the new infrastructures)
