### ISSUE TITLE
Bug in RDF generation

### ISSUE THREAD

**Issue by dayures** [landportal/drupal#76]
There is a bug when Drupal generates the RDF. The source of this bug is the module "rdfx". This module is a dependency of "drupal\modules\landlibrary\modules\rdf_indexer"

The bug is already documented and fixed in 
https://www.drupal.org/node/1351364

The actual version of module rdfx running in landportal.info is 7.x-2.0-alpha4. There are no updated released. The fix is in the development branch (that, actually, has not been changed since february 2014).

As a side comment, I think that this module is not a dependency of the landlibrary, as it is used to upload RDF content not only from the landlibrary.

**Comment by semberryltd** [comment]
Just to remind you that the module was changed a little bit to fit for the Landportal needs,
so don t update it from drupal.org, but keep it from git branch.
cheers
A

**Comment by dayures** [comment]
Hi Antonella,

thank you very much for the reminder! 

@jcr please, take it into account this comment.

**Comment by dayures** [comment]
@semberryltd I was checking the code but I haven't found the changes. Could you point out what was changed ? Thanks in advanced

**Comment by dayures** [comment]
The changes commented by @semberryltd have been applied in the repository https://github.com/landportal/rdfx

**Comment by dayures** [comment]
The bug in the RDF generation as been fixed in landportal/rdfx@f24b51a53e81df568338a9a269214b9bf55ae838

**Comment by dayures** [comment]
As side documentation about retrieve RDF content of a taxonomy term and URL patterns

> Modules such as [RestWS](https://www.drupal.org/project/restws) and RDFx rely on the entity API to answer REST calls such as node/1.rdf and return data associated with node/1 in RDF. This works well for comments and user, but fails for taxonomy terms. Users cannot add .rdf to taxonomy/term/1, they need to go to taxonomy_term/1.rdf, which is a usability issue and inconsistent with the way nodes and users work. ([from taxonomy_term does not match expected path for taxonomy terms](https://www.drupal.org/node/1673076))

I don't know if its a bug or a feature. There are several comments/issues raised about it:

- [restws_resource_uri() breaks default entities URI pattern](https://www.drupal.org/node/1719730)
- [taxonomy_term does not match expected path for taxonomy terms](https://www.drupal.org/node/1719730)
