### ISSUE TITLE
Language translation issue with user location

### ISSUE THREAD

**Issue by lmeggiolaro** [landportal/drupal#78]
The country shows up in Spanish on the English page of user profiles:
![glitchprofiles](https://cloud.githubusercontent.com/assets/6312042/15607642/c6330b58-2414-11e6-8158-14b6898ad538.png)

**Comment by jcr** [comment]
for me, whatever is the language I choose on the website it always shows in English

**Comment by aostroverkhov** [comment]
@jcr looks the address fields simply aren't configured to be translatable, do they need to be?

**Comment by jcr** [comment]
After further testing last week, this actually now works as expected.
The Location field will translate in the language in which the Organization is displayed.
Note for Organizations:
 - if they have no language (neutral) they will display in EN and all other language - the location fields will be in EN as well.
 - if they have a specific language they will *only* display in that language and the location will be translated (ie: if you set and org to EN and do not translate it, it will not show up in the other lang.)
