### ISSUE TITLE
Mismatch in prefixes between Drupal and Virtuoso

### ISSUE THREAD

**Issue by dayures** [landportal/drupal#79]
"dc" prefix in Drupal is linked to http://purl.org/dc/terms/
"dc" prefix in Virtuoso is linked to http://purl.org/dc/elements/1.1/

In order to fix it, the dc prefix in Drupal must be change into the wellknown "dct". Also, all the dc:XXX rdf mappings must be updated

**Comment by dayures** [comment]
Changed files directly in production.
Attached patch for rdf module (provided by Drupal core).
[rdf-dc-namespace.txt](https://github.com/landportal/drupal/files/612954/rdf-dc-namespace.txt)

@jcr is possible to apply this patch using the drush makefile (take into account that rdf is a module provided by Drupal core) ?

**Comment by dayures** [comment]
@jcr, please apply the changes if there are not other issues

please find attached an improved patch (renamed to .txt)
[change-dc-to-dct.txt](https://github.com/landportal/drupal/files/766584/change-dc-to-dct.txt) 

and a possible patch for the "make" files
[make.txt](https://github.com/landportal/drupal/files/766643/make.txt)

**Comment by jcr** [comment]
patch in prod.
This will not stick when Drupal upgrades.
Maybe think about a patch to submit to drupal core rdf module?

**Comment by dayures** [comment]
fixed in 55373668d1bce3f1b981914796703a921b0477a8
