### ISSUE TITLE
Missed country in country taxonomy (Tanzania - TZA)

### ISSUE THREAD

**Issue by dayures** [landportal/drupal#80]
I have realized that the country "Tanzania" (iso3 code: TZA) is not in the country taxonomy. @jcr I don't know if it was missed during the integration process of multiples country/region/area. After check it, please, comment what should be the next step (and the appropiate person to do it). Thanks.

**Comment by lisettemeij** [comment]
It actually is in the country taxonomy, under "United Republic of Tanzania". Or are you talking about a new taxonomy?

**Comment by dayures** [comment]
In this taxonomy https://landportal.info/admin/structure/taxonomy/countries

**Comment by lisettemeij** [comment]
Ok sorry, you are right there is no United Republic of Tanzania there ;-)

**Comment by dayures** [comment]
Manually added in Country taxonomy

https://landportal.info/voc/countries/tanzania
