### ISSUE TITLE
Land Library Admin view doesn't work

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#82]
The Land Library admin view doesn't seem to work anymore. I can't filter for Publication date or Date updated. I need to do this for the DFID report. It just says "illegal choice" or something. See the attached screenshot.

CAn we fix this??
![screen shot 2016-06-08 at 18 04 32](https://cloud.githubusercontent.com/assets/6312043/15901442/9b45fb9c-2da3-11e6-9c47-17ee35f5cd1f.png)

**Comment by jcr** [comment]
fixed d743b78
