### ISSUE TITLE
Log in issue

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#83]
I have an issue when I log in on the Land Portal. On the old server, I used to do this:

- I was logged in on tab A in my browser. When I open LP website in tab B, I'm not logged in there.
- I simply log in on tab B.

Now that doesn't seem to work anymore:
- I am logged in on tab A in my browser. When I open LP website in tab B, I'm not logged in there.
- I try to log in on tab B, but get the following error:

https://accounts.google.com/o/oauth2/auth?client_id=158143040800-fqrfqg8517na17dl6r7vve6vus0dkesl.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flandportal.info%2Fhybridauth%2Fendpoint%3Fhauth.done%3DGoogle&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&access_type=offline

(see screenshot).

Any idea?
![screen shot 2016-06-13 at 11 51 35](https://cloud.githubusercontent.com/assets/6312043/16003499/33919d90-315d-11e6-8d68-7cf463f25e49.png)

**Comment by jcr** [comment]
fixed, FTR
 - set some redirection to force https on /user and /admin
 - configured drupal to allow mixed https
