### ISSUE TITLE
Organizational logos and job titles no longer appear on individual profiles

### ISSUE THREAD

**Issue by lmeggiolaro** [landportal/drupal#85]
The organizational logos and job titles seem to no longer appear on user profiles. This was working fine until last week when I created this profile and confirmed that everything looked fine with the user: 

https://www.landportal.info/users/nicky-rehbock

The organization and job title are linked and included in the user profile, but no longer appear.

**Comment by jcr** [comment]
according to the site settings in manage display (user account and work profile) it should work and be displayed.
Is this (again) something you guys hardcoded?

**Comment by aostroverkhov** [comment]
@jcr fixed, please check http://beta.landportal.info/users/nicky-rehbock
not sure though if the styling is 100% correct

**Comment by jcr** [comment]
I still don't see any organization / position in her profile in there

**Comment by aostroverkhov** [comment]
@jcr sorry broke when merging with master yesterday, fixed now - http://beta.landportal.info/users/nicky-rehbock

**Comment by jcr** [comment]
ok , now it shows on the full profile page. We will see for a better design in the next Milestone 
"2.3.2 - Theme"
