### ISSUE TITLE
Fixed relationships overarching categories - concepts: maximum characters

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#86]
I've posted this here before, but I can't add all the fixed relationships between the overarching categories and the concepts because there is a maximum amount of characters that's been reached.

Can this be removed? 

+ the fixed relationships between concepts and overarching categories/themes actually need to be implemented still. So that those resources that have been tagged with a concept that's fixed to an OA or a Theme, the OA or Theme is also tagged to the resource.

Thanks!

**Comment by jcr** [comment]
fixed
