### ISSUE TITLE
Search result view - alignment of resources without a thumbnail

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#87]
In the search result view, can we change the alignment of the resources without a thumbnail so that the text aligns with those resource that do have a thumbnail? (see screencapture).

Now the text is aligned completely to the left, where the thumbnail of a resource appears first. Seems a little cluttered.
![screen shot 2016-06-15 at 14 16 56](https://cloud.githubusercontent.com/assets/6312043/16079479/0b7e72da-3304-11e6-9fea-b91f65ee1819.png)

**Comment by jcr** [comment]
https://landportal.info/search/all/Land%20Rights
needs to be fixed

1/ the search input needs the new style
2/ on the results , we need to review each CT "search listing" display and fix / improve (beware we now have plenty of hardcoded templates in the theme)

If we globally move to a 'real' bootstrap-based theme (which is / was the goal of this milestone), I believe this will all come nicely together with a minimum efforts.

**Comment by jcr** [comment]
Closing this, by default now all CT have a 'no preview available' one (in 4x3) This is already online
The 'new search now have more proper 'listing' view mode, the style might still need to be adjusted or improved but we're now better off in general.
