### ISSUE TITLE
Individual profile pictures no longer resized and misplaced 

### ISSUE THREAD

**Issue by lmeggiolaro** [landportal/drupal#88]
The profile pictures of individuals no longer appear automatically resized and in position, but now appear in full size and underneath the text.

**Comment by jcr** [comment]
The major issue here is to basically not have a plan a any specification on what is the final design / goal.
This is valid for both the user profile page and the teaser/preview (as shown in Debates or listings).

Therefor bouncing that to next MS.

**Comment by jcr** [comment]
this is all re-done and cleaned. Visible on stage and will be pulled into production this morning.
