### ISSUE TITLE
Overarching Categories + Themes appear different on news/debate than on LLR

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#90]
See the attached screenshots. shouldn't we place all the tags similar everywhere?

<img width="1280" alt="screen shot 2016-06-21 at 16 49 49" src="https://cloud.githubusercontent.com/assets/6312043/16225302/38d92a06-37d0-11e6-8f80-b6545769603e.png">
<img width="1280" alt="screen shot 2016-06-21 at 15 42 53" src="https://cloud.githubusercontent.com/assets/6312043/16225330/5a6f4092-37d0-11e6-9aa2-bc01cd61d5e4.png">

**Comment by lisettemeij** [comment]
I dn't think the themes are appearing at all, now I look at it in more detail

**Comment by lisettemeij** [comment]
I changed this myself for the organizational profile, Not a permanent change (because it's still not ideal, but at least it is something):

![screen shot 2016-08-11 at 14 33 42](https://cloud.githubusercontent.com/assets/6312043/17588633/9fabe1ec-5fd0-11e6-8c62-c0402c9b95a9.png)

**Comment by jcr** [comment]
OK now all resources (news/blogs/events/debates/orgs/...) should be aligned.
it is not ideally placed or styled but consistent.
Styling and all will be improved in the next Milestone
