### ISSUE TITLE
Location source in LL resource - unlink from Regions taxonomy

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#94]
Hi,

The 'Location of the source' in the Land Library Form links to the Regions taxonomy and enables users to add a lot of different locations to the regions taxonomy, making that taxonomy a mess. I've already deleted a few before to clean it up. But since users will want to put cities or regions and we are not going to use this information to search for something, let's make this free text.

**Comment by jcr** [comment]
I am closing this as it makes no or little sense. We don't solve problems by smashing the existing things or giving a apparent solution to a problem not understood.
The issue with region/country is much more deep and complicated than this.
But in short:
1/ this should become a much broader 'geo' taxonomy
2/ this is ok (not ideal or good) to have any kind of geography concepts in there, they will be matched again WKT once we deployed the proper technology layers behind.
3/ no no no to 'free text' (or while we're at it let's turn all the LP back to static HTML pages!)
