### ISSUE TITLE
Layout of Fields in Library Resource Form (probably others as well)

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#97]
Hi,

There should be more consistency in the layout for the forms. The layout differs to what kind of field it is (e.g. if there is something with multiple rows that users can add, there is a greyish header and sometimes an extra border goes around a field without there being any apparent reason for it), see the screenshot attached:

![screen shot 2016-07-06 at 13 28 35](https://cloud.githubusercontent.com/assets/6312043/16616532/10128090-437e-11e6-9004-5e6dd36e1cb6.png)

The difference in the layout is not logical and actually makes the form a bit messy, because the grouping now doesn't follow a logical order (it seems like a separate group or something is added).

Can we change the layout for all the fields to just a bold text with the field below it (like Document ID/Resource type in the screenshot)?

Thanks!

**Comment by jcr** [comment]
FTR, this view was only for administrators, the contributors have an even worst view in terms of design.
This is improved in the new version and admin (LP staff) are now using the same forms as contributors.

For the consistency of the fields which is IMHO what matter here (when creating a news, LLR or an event - the 'same' fields should have consistent name and way to display - which should already very largely be the case compare to 1y ago).
Still, we should have a quick pass at all our CT (manage fields section) and make it even better.

Back to the 'look and feel' the grouping thing you describe comes from Drupal core elements. This will also be changed (for the better) in the new version and will be much more easy to tweak (remember the quick test I made on the LLR form and shared with you back 2-3 weeks ago?).

**Comment by jcr** [comment]
massively improved by today's release.
To be continued...
