### ISSUE TITLE
Geographical focus fields (countries) suddenly all turned to Benin

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#98]
Geographical focus fields (countries) suddenly all turned to Benin. In the admin view, it doesn't show up like that, but when I search for Benin in Geographical focus I get 15,000 results (so basically, all the resources).

See this screenshot for example:
![screen shot 2016-07-06 at 17 03 36](https://cloud.githubusercontent.com/assets/6312043/16622846/e26191d6-439b-11e6-8da2-7b3750ec3e25.png)

The admin view does still show the normal countries/geographical focus tags so the information should still be there, we just have to figure out why it turns into 'Benin' on the pages.

**Comment by lisettemeij** [comment]
I changed this manually for the Uttaran publications. The Geographical focus seemed to have changed to Benin (though country tag was still Bangladesh - but that is deprecated and shows in the admin view).

If this somehow just changed - we need to figure out how and make sure it doesn't happen again.

**Comment by jcr** [comment]
This is a really odd bug that seem to have happened only this time (maybe due to some cache clear / field cleaning)
