### ISSUE TITLE
Delete Acronym on bottom organizational profile teaser view

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#99]
Hi,

Can we delete the acrononym from the organizational profile teaser view? (see below)
<img width="1280" alt="screen shot 2016-07-08 at 11 03 34" src="https://cloud.githubusercontent.com/assets/6312043/16682667/eaaa0c86-44fb-11e6-878d-949d099bcc24.png">
Not really necessary I think and not all organizational profiles are filled in like that:)

**Comment by jcr** [comment]
done
